- gradle.properties
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/BoundedContext.kt
- wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/BoundedContextResolver.kt
- wow-core/src/main/kotlin/me/ahoo/wow/configuration/WowMetadata.kt
- wow-core/src/main/kotlin/me/ahoo/wow/id/CosIdAggregateIdGeneratorFactory.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/AggregateDispatcher.kt
> feat: custom id

- deploy/example-deployment.yml
- gradle.properties
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/DomainEventBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotStrategySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/InMemoryCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/InMemoryDomainEventBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/MessageBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/AbstractMetricDecorator.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricDomainEventBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricEventStore.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricSnapshotRepository.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/Metrics.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/InMemoryCommandBusTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/LocalFirstCommandBusTest.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/AbstractKafkaBus.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaCommandBus.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaDomainEventBus.kt
- wow-mongo/src/init-schema/init-schema-mysql.js
- wow-mongo/src/init-schema/init-schema.js
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandGatewayAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandProperties.kt
- feat: support `LocalFirstCommandBus`
- feat: support `source` for `AbstractMetricDecorator`
> feat: support `LocalFirstCommandBus`

- gradle.properties
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/LocalCommandBusInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/LocalEventBusInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingMessageBus.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/MonoTraceTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalCommandBusTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalEventBusTest.kt
- feat: support TracingLocalMessageBus
> feat: support TracingLocalMessageBus

- .idea/modules/wow-spring-boot-starter/Wow.wow-spring-boot-starter.main.iml
- gradle.properties
- test/wow-tck/build.gradle.kts
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/command/CommandDispatcherSpec.kt
- wow-core/build.gradle.kts
- wow-core/src/main/kotlin/me/ahoo/wow/infra/idempotency/BloomFilterIdempotencyChecker.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/idempotency/IdempotencyChecker.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/dispatcher/AbstractDispatcher.kt
- wow-core/src/test/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotDispatcherTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/infra/idempotency/BloomFilterIdempotencyCheckerTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/infra/idempotency/NoOpIdempotencyCheckerTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandGatewayAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandProperties.kt
- feat: support customize `BloomFilterIdempotencyChecker`
> feat: support customize `BloomFilterIdempotencyChecker`

- gradle.properties
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/MonoLocalBusTrace.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingMessageBus.kt
- refactor: `TracingLocalCommandBus` and `TracingLocalEventBus`
> refactor: `TracingLocalCommandBus` and `TracingLocalEventBus`

- example/example-server/src/init-schema/init-schema.js
- gradle.properties
- wow-mongo/src/init-schema/init-schema.js
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/SnapshotSchemaInitializer.kt
- feat: Automatically create snapshot indexes.
> feat: Automatically create snapshot indexes.

- .github/workflows/codecov.yml
- gradle.properties
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotRepositorySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/InMemorySnapshotRepository.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotRepository.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricSnapshotRepository.kt
- wow-core/src/test/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotDispatcherTest.kt
- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/ElasticsearchSnapshotRepository.kt
- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/SnapshotIndexNameConverter.kt
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/MongoSnapshotRepository.kt
- wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/R2dbcSnapshotRepository.kt
- wow-r2dbc/src/test/kotlin/me/ahoo/wow/r2dbc/R2dbcSnapshotRepositoryTest.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/BatchRegenerateSnapshotHandlerFunction.kt
- feat: support `ElasticsearchSnapshotRepository.scrollAggregateId`
> feat: support `ElasticsearchSnapshotRepository.scrollAggregateId`

- gradle.properties
- test/wow-it/src/test/kotlin/me/ahoo/wow/it/KafkaLauncher.kt
- test/wow-it/src/test/kotlin/me/ahoo/wow/it/KafkaMongoCommandDispatcher.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/DomainEventBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/command/CommandDispatcherSpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/MessageBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricDomainEventBus.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/AbstractKafkaBus.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaCommandBus.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaDomainEventBus.kt
- wow-kafka/src/test/kotlin/me/ahoo/wow/kafka/KafkaCommandBusTest.kt
- wow-kafka/src/test/kotlin/me/ahoo/wow/kafka/KafkaCommandDispatcherTest.kt
- wow-kafka/src/test/kotlin/me/ahoo/wow/kafka/KafkaDomainEventBusTest.kt
- wow-kafka/src/test/kotlin/me/ahoo/wow/kafka/KafkaLauncher.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingMessageBus.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalCommandBusTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalEventBusTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/kafka/KafkaAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/kafka/KafkaAutoConfigurationTest.kt
- feat: add `AutoCloseable` to `MessageBus`
> feat: add `AutoCloseable` to `MessageBus`

- deploy/example-deployment.yml
- gradle.properties
- wow-core/src/main/java/me/ahoo/wow/infra/accessor/method/FastInvoke.java
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/constructor/ConstructorAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/constructor/ObjectFactory.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/MethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/reactive/BlockingMonoMethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/reactive/FluxMonoMethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/reactive/PublisherMonoMethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/reactive/SimpleMonoMethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/method/reactive/SyncMonoMethodAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/property/PropertySetter.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MethodMessageHandler.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/SimpleCommandAggregateFactory.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/StateAggregateFactory.kt
- wow-core/src/test/kotlin/me/ahoo/wow/infra/accessor/method/SimpleMethodAccessorTest.kt
- refactor: Enhance `MethodAccessor.invoke` performance
> refactor: Enhance `MethodAccessor.invoke` performance.

- gradle.properties
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/handler/MessageExchange.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/RetryableAggregateProcessor.kt
- fix: unnecessary exception propagation on retry
> fix: unnecessary exception propagation on retry

- gradle.properties
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/RetryableAggregateProcessor.kt
- fix: missing ServiceProvider
> fix: missing ServiceProvider

- wow-core/src/main/kotlin/me/ahoo/wow/scheduler/AggregateSchedulerSupplier.kt
> feat: rename Scheduler

- gradle.properties
- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/WowInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/aggregate/AggregateInstrumenter.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/CommandParser.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/CommandHeaders.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/CommandRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/DeleteAggregateRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/EventCompensateRouteAppender.kt
- feat: support `request_id` for `WowInstrumenter`
- feat: support `Command-Request-Id` for `CommandRoute`
> feat: support `Command-Request-Id` for `CommandRoute`

- gradle.properties
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotStrategySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SimpleSnapshotStrategy.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotSink.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotStrategy.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/handler/MessageExchange.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricSnapshotStrategy.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaSnapshotSink.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/KafkaTopic.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/snapshot/SnapshotAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/snapshot/SnapshotProperties.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/kafka/KafkaAutoConfiguration.kt
- feat: support `SnapshotSink`
> feat: support `SnapshotSink`

- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfigurationTest.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/AggregateRouterFunctionAutoRegistrar.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/SnapshotSinkHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/RoutePaths.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/SnapshotSinkRouteAppender.kt
- feat: support `SnapshotSinkHandlerFunction`
> feat: support `SnapshotSinkHandlerFunction`

- gradle.properties
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/SnapshotSinkHandlerFunction.kt
- refactor: change `flatMap` to `flatMapSequential` to try to ensure the order of snapshots.
> refactor: change `flatMap` to `flatMapSequential` to try to ensure the order of snapshots.

- gradle.properties
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/DefaultAggregateId.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/MaterializedNamedAggregate.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/ErrorHttpStatusMapping.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/ErrorHttpStatusMappingTest.kt
- feat: Generate hashCode as early as possible to improve Map performance.
> feat: Generate hashCode as early as possible to improve Map performance.

- gradle.properties
- test/wow-mock/src/main/kotlin/me/ahoo/wow/eventsourcing/mock/DelayEventStore.kt
- test/wow-mock/src/main/kotlin/me/ahoo/wow/eventsourcing/mock/DelaySnapshotRepository.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotRepositorySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventStore.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/InMemoryEventStore.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/InMemorySnapshotRepository.kt
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotRepository.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricEventStore.kt
- wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricSnapshotRepository.kt
- wow-core/src/test/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotDispatcherTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/AggregateIdTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/command/MockDelayEventStoreCommandDispatcherTest.kt
- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/ElasticsearchSnapshotRepository.kt
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/MongoEventStore.kt
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/MongoSnapshotRepository.kt
- wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/R2dbcEventStore.kt
- wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/R2dbcSnapshotRepository.kt
- wow-r2dbc/src/test/kotlin/me/ahoo/wow/r2dbc/R2dbcEventStoreTest.kt
- wow-r2dbc/src/test/kotlin/me/ahoo/wow/r2dbc/R2dbcSnapshotRepositoryTest.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/handler/SnapshotSinkHandler.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/AggregateRouterFunctionAutoRegistrar.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/BatchRegenerateSnapshotHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/SnapshotSinkHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/BatchRegenerateSnapshotRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/SnapshotSinkRouteAppender.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/BatchRegenerateSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/SnapshotSinkHandlerFunctionTest.kt
- feat: add `scrollAggregateId` to `EventStore`.
> feat: add `scrollAggregateId` to `EventStore`.

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/EventStreamKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/RedisEventStore.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/SnapshotKeyConverter.kt
- wow-redis/src/main/resources/event_steam_append.lua
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/DefaultSnapshotKeyConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/EventStreamKeyConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/RedisEventStoreTest.kt
- feat: support `DuplicateRequestId` check for `RedisEventStore`
> feat: support `DuplicateRequestId` check for `RedisEventStore`

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/prepare/PrepareKeySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/infra/prepare/PreparedValue.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/EventStreamKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/prepare/PrepareKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/prepare/RedisPrepareKey.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/prepare/RedisPrepareKeyFactory.kt
- wow-redis/src/main/resources/prepare_prepare.lua
- wow-redis/src/main/resources/prepare_reprepare.lua
- wow-redis/src/main/resources/prepare_reprepare_with_old_value.lua
- wow-redis/src/main/resources/prepare_rollback.lua
- wow-redis/src/main/resources/prepare_rollback_with_old_value.lua
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/prepare/ObjectRedisPrepareKeyTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/prepare/RedisPrepareKeySpec.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/prepare/StringRedisPrepareKeyTest.kt
- feat: support `RedisPrepareKey`
> feat: support `RedisPrepareKey`

- wow-redis/src/main/kotlin/me/ahoo/wow/redis/EventStreamKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/RedisWrappedKey.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/prepare/PrepareKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/prepare/RedisPrepareKey.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/RedisWrappedKeyTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/mongo/MongoEventSourcingAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/ConditionalOnPrepareEnabled.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareProperties.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/redis/RedisEventSourcingAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/redis/RedisEventSourcingAutoConfigurationTest.kt
- feat: support `PrepareAutoConfiguration`
> feat: support `PrepareAutoConfiguration`

- wow-core/src/main/kotlin/me/ahoo/wow/messaging/ReceiverGroup.kt
> refactor: `ReceiverGroup`

- gradle.properties
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/GivenInitializationCommand.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/command/CommandMessage.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Header.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/InMemoryCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/SimpleCommandMessage.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/DomainEventStream.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/InMemoryDomainEventBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/DefaultHeader.kt
- wow-core/src/test/kotlin/me/ahoo/wow/messaging/DefaultHeaderTest.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/MessageExchangeTextMapGetter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/MessageTextMapSetter.kt
- feat: support `copy` for `CommandMessage`
> feat: support `copy` for `CommandMessage`

- gradle.properties
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Header.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Message.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/InMemoryCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/InMemoryDomainEventBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/DefaultHeader.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/SimpleCommandMessageTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/messaging/DefaultHeaderTest.kt
- wow-kafka/src/main/kotlin/me/ahoo/wow/kafka/AbstractKafkaBus.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/MessageTextMapSetter.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/MessageTextMapSetterTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalCommandBusTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalEventBusTest.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/bus/AbstractRedisMessageBus.kt
- feat: support `ReadOnlyHeader`  to prevent illegal writing.
> feat: support `ReadOnlyHeader`  to prevent illegal writing.

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/AggregateIdAttributesExtractor.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/TraceFlux.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/TraceMono.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/Tracing.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/WowInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/eventsourcing/EventStoreInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/eventsourcing/TracingEventStore.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/snapshot/SnapshotRepositoryInstrumenter.kt
- wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/snapshot/TracingSnapshotRepository.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/eventsourcing/TracingEventStoreTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalCommandBusTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/messaging/TracingLocalEventBusTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/snapshot/TracingSnapshotRepositoryTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/opentelemetry/TracingBeanPostProcessor.kt
- feat: support `TracingEventStore` / `TracingSnapshotRepository`
> feat: support `TracingEventStore` / `TracingSnapshotRepository`

- example/example-server/build.gradle.kts
- wow-core/src/main/kotlin/me/ahoo/wow/command/CommandFactory.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/SimpleCommandMessage.kt
- demo: add `cosid-spring-redis` to example
> demo: add `cosid-spring-redis` to example

- wow-api/src/main/kotlin/me/ahoo/wow/api/Copyable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Header.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/LocalFirstMessageBus.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/LocalFirstCommandBusTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandProperties.kt
- feat: support `LocalFirstMessageBus` Spec
> feat: support `LocalFirstMessageBus` Spec

- deploy/script/clickhouse.sql
- doc: Update `StateEvent` sync to clickhouse script
> doc: Update `StateEvent` sync to clickhouse script

- README.md
- README.zh-CN.md
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/bus/AggregateTopicConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/bus/RedisStateEventBus.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/bus/RedisStateEventExchange.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/eventsourcing/EventStreamKeyConverter.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/eventsourcing/RedisEventStore.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/eventsourcing/RedisSnapshotRepository.kt
- wow-redis/src/main/kotlin/me/ahoo/wow/redis/eventsourcing/SnapshotKeyConverter.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/bus/DefaultCommandTopicConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/bus/DefaultEventStreamTopicConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/bus/DefaultStateEventTopicConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/bus/RedisStateEventBusTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/eventsourcing/DefaultSnapshotKeyConverterTest.kt
- wow-redis/src/test/kotlin/me/ahoo/wow/redis/eventsourcing/EventStreamKeyConverterTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/kafka/KafkaAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/redis/RedisMessageBusAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/redis/RedisMessageBusAutoConfigurationTest.kt
- feat: support `RedisStateEventBus`
> feat: support `RedisStateEventBus`

- example/example-server/src/main/resources/application.yaml
- gradle.properties
- wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotDispatcher.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/LocalFirstMessageBus.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/handler/ExchangeAck.kt
- wow-core/src/test/kotlin/me/ahoo/wow/messaging/handler/ExchangeAckTest.kt
- feat: add `filterThenAck`  extension function
> feat: add `filterThenAck`  extension function

- gradle.properties
- wow-core/src/main/kotlin/me/ahoo/wow/route/AggregateRoutePathSpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/route/IgnoreTenantAggregateRoutePathSpec.kt
- wow-core/src/test/kotlin/me/ahoo/wow/route/AggregateRoutePathSpecTest.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/handler/RegenerateStateEventHandler.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/BatchRegenerateSnapshotHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/BatchRegenerateSnapshotRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/CommandRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/RegenerateStateEventRouteAppender.kt
- feat: add `IgnoreTenantAggregateRoutePathSpec`
> feat: add `IgnoreTenantAggregateRoutePathSpec`

- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnCommand.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnError.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnEvent.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnMessage.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnSourcing.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/FunctionKind.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/FunctionMetadataParser.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MessageFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MethodFunctionMetadata.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MethodMessageHandler.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/DefaultDeleteAggregateFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt
- wow-core/src/test/kotlin/me/ahoo/wow/event/DomainEventDispatcherTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/messaging/function/MethodFunctionMetadataTest.kt
- feat: support `FunctionKind` for `MessageFunction`.
> feat: support `FunctionKind` for `MessageFunction`.

- wow-core/src/main/kotlin/me/ahoo/wow/event/compensation/DomainEventCompensator.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/compensation/StateEventCompensator.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/compensation/EventCompensator.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/event/EventAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/state/StateAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/event/EventAutoConfigurationTest.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/state/StateAutoConfigurationTest.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfigurationTest.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/handler/RegenerateStateEventHandler.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/AggregateRouterFunctionAutoRegistrar.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/RegenerateStateEventFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/DomainEventCompensateRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/EventCompensateRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/RegenerateStateEventRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/appender/StateEventCompensateRouteAppender.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/compensation/DomainEventCompensateHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/compensation/EventCompensateHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/compensation/StateEventCompensateHandlerFunction.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/DomainEventCompensateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/RegenerateStateEventHandlerFunctionTest.kt
- feat: support `StateEventCompensator`
> feat: support `StateEventCompensator`

- example/example-domain/src/main/kotlin/me/ahoo/wow/example/domain/order/Order.kt
- gradle.properties
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/mock/MockAggregate.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/FunctionMetadataParser.kt
- feat: support `OnError` for `Command`
> feat: support `OnError` for `Command`

- gradle.properties
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/BusProperties.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandProperties.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/event/EventProperties.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/state/StateProperties.kt
- feat: enhance spring-boot auto-configuration hints
> feat: enhance spring-boot auto-configuration hints

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/NotifierFilters.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/processor/ProcessorInfo.kt
- wow-core/src/test/kotlin/me/ahoo/wow/annotation/AggregateAnnotationParserTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifierTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SimpleWaitStrategyRegistrarTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/event/ExchangeEventFunctionKtTest.kt
- wow-opentelemetry/src/test/kotlin/me/ahoo/wow/opentelemetry/ExchangeTraceMonoTest.kt
- refactor: `MonoCommandWaitNotifier`
> refactor: `MonoCommandWaitNotifier`

- gradle.properties
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt
- feat: Enhanced `SagaVerifier` to support flow command validation.
> feat: Enhanced `SagaVerifier` to support flow command validation

- example/transfer/example-transfer-domain/src/main/java/me/ahoo/wow/example/transfer/domain/Account.java
- example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/AccountKTest.kt
- update lockAmount api 
- add unit test.
> update lockAmount api and add unit test.

- compensation/wow-compensation-api/src/main/kotlin/me/ahoo/wow/compensation/api/ApplyExecutionSuccess.kt
- compensation/wow-compensation-api/src/main/kotlin/me/ahoo/wow/compensation/api/CreateExecutionFailed.kt
- compensation/wow-compensation-api/src/main/kotlin/me/ahoo/wow/compensation/api/IExecutionFailedState.kt
- compensation/wow-compensation-api/src/main/kotlin/me/ahoo/wow/compensation/api/PrepareCompensation.kt
- compensation/wow-compensation-core/src/test/kotlin/me/ahoo/wow/compensation/core/CompensationSagaTest.kt
- compensation/wow-compensation-domain/src/main/kotlin/me/ahoo/wow/compensation/domain/CompensationSpec.kt
- compensation/wow-compensation-domain/src/main/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailed.kt
- compensation/wow-compensation-domain/src/main/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedState.kt
- compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/DefaultCompensationSpecTest.kt
- compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedTest.kt
- compensation/wow-compensation-server/src/main/kotlin/me/ahoo/wow/compensation/server/CompensationConfiguration.kt
> feat: support `CompensationSpec`

- compensation/wow-compensation-server/src/main/resources/application.yaml
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/DomainEventConverter.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/EventStreamConverter.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/StateEventConverter.kt
- wow-openapi/src/main/resources/META-INF/services/io.swagger.v3.core.converter.ModelConverter
- feat: add `StateEventConverter`/`EventStreamConverter`/`DomainEventConverter` to adapt Wow Serializer - OpenAPI-Schema
> feat: add `StateEventConverter`/`EventStreamConverter`/`DomainEventConverter` to adapt Wow Serializer - OpenAPI-Schema

- documentation/docs/guide/getting-started.md
- update documentation/docs/guide/getting-started.md that Windows template folder path
> update getting-started that Windows template folder path

- gradle/libs.versions.toml
> Revert "fix(deps): update dependency io.swagger.core.v3:swagger-core-jakarta to v2.2.26"

- gradle/libs.versions.toml
> Revert "fix(deps): update dependency me.ahoo.coapi:coapi-bom to v1.9.0"

- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/eventsourcing/ElasticsearchEventStore.kt
- Default batch size increased from 100 to 10000
- Added batchSize parameter to ElasticsearchEventStore constructor
- Updated searchEventStream method to use dynamic batch size
> perf(es-event-store): increase batch size for event stream loading

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/GivenInitializationCommand.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/compensation/DomainEventCompensator.kt
- wow-core/src/main/kotlin/me/ahoo/wow/event/compensation/StateEventCompensator.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/compensation/EventCompensator.kt
- wow-core/src/test/kotlin/me/ahoo/wow/event/compensation/DomainEventCompensatorTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/event/compensation/StateEventCompensatorTest.kt
- Update EventCompensator interface to use generic type E extending DomainEventStream
- Add compensate function to EventCompensator interface
- Implement compensate function in DomainEventCompensator and StateEventCompensator
- Refactor resend function in both compensators to use the new compensate method
> refactor(compensation): enhance EventCompensator with generic type and add compensate function

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt
- Enhance error message with stack trace information when domain event stream is null
- Improve test diagnostics by providing more detailed failure information
> test(wow-test): improve error handling in expectEventStream

- documentation/docs/.vitepress/theme/global.css
- documentation/docs/.vitepress/theme/index.ts
- documentation/package-lock.json
- documentation/package.json
- Upgrade VitePress from 1.0.0-rc.34 to 1.5.0
- Add medium-zoom dependency for image zoom functionality
- Create global.css file for custom styling
- Implement mediumZoom in theme setup for image zoom
> docs(documentation): upgrade VitePress and add medium-zoom

- wow-query/src/main/kotlin/me/ahoo/wow/query/dsl/PagedQueryDsl.kt
- wow-query/src/main/kotlin/me/ahoo/wow/query/dsl/QueryableDsl.kt
- Add direct setter methods for pagination, projection, condition, and sort
- Simplify DSL usage by allowing direct property setting
- Improve code readability and flexibility in constructing queries
> feat(query): add direct property setters for query elements

- .idea/inspectionProfiles/Project_Default.xml
- example/example-server/src/main/kotlin/me/ahoo/wow/example/server/cart/CartController.kt
- Add new POST endpoint /cart/{userId} to send custom commands
- Implement functionality to add items to user's cart using AddCartItem command
- Update CartController to include new method for handling custom commands
> feat(example-server): add customize send cmd endpoint

- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/CountQueryHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/ListQueryHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/PagedQueryHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/RewriteRequestCondition.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/SingleQueryHandlerFunction.kt
- Create RewriteRequestCondition class to encapsulate tenant ID rewriting logic
- Update query handler functions to use RewriteRequestCondition for tenant ID handling
- Remove direct calls to getTenantId from query handler functions
- Simplify query handling code by using the new RewriteRequestCondition class
> refactor(query): extract tenant ID handling logic

- example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaTest.kt
- example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt
- Add ownerId support to GivenStage and WhenStage
- Refactor test stages to use new ownerId parameter
- Update CartSagaTest and CartTest to use new ownerId functionality
- Modify DefaultAggregateVerifier to handle owner id
> test(aggregate): add owner id support and refactor test stages

- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/ErrorHttpStatusMapping.kt
- Map ErrorCodes.ILLEGAL_ACCESS_OWNER_AGGREGATE to HttpStatus.FORBIDDEN
> feat(exception): add mapping for ILLEGAL_ACCESS_OWNER_AGGREGATE errorcode

- wow-elasticsearch/src/main/resources/templates/wow-event-stream-template.json
- wow-elasticsearch/src/main/resources/templates/wow-snapshot-template.json
- Add ownerId field to wow-event-stream-template.json
- Add ownerId field to wow-snapshot-template.json
> feat(elasticsearch): add ownerId field to event stream and snapshot templates

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/GlobalRouteSpecFactory.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandFacadeRouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandRequestParameters.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandResponses.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandRouteSpec.kt
- Extract CommandRequestParameters into separate file
- Extract CommandResponses into separate file
- Update imports and usages in related files
- Add EmptyClassConverter for handling empty schemas
> refactor(wow-openapi): extract CommandRequestParameters and CommandResponses

- documentation/docs/guide/getting-started.md
- Update the project template zip file link to version 5.3.8
> docs(getting-started): update project template version

- wow-openapi-joda-money/src/main/kotlin/me/ahoo/wow/joda/money/converter/MoneyConverter.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/ComponentRef.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt
- Update OpenAPI specification version to3.1
- Improve model conversion by using ModelConverters with correct version
> feat(openapi): upgrade to OpenAPI3.1 and enhance model conversion

- .idea/modules/wow-cocache/Wow.wow-cocache.main.iml
- wow-cocache/build.gradle.kts
- wow-cocache/src/main/kotlin/me/ahoo/wow/cache/LoadCacheSourceConfiguration.kt
- wow-cocache/src/main/kotlin/me/ahoo/wow/cache/QueryApiCacheSource.kt
- wow-cocache/src/main/kotlin/me/ahoo/wow/cache/QueryServiceCacheSource.kt
- wow-cocache/src/main/kotlin/me/ahoo/wow/cache/StateCacheSource.kt
- wow-cocache/src/test/kotlin/me/ahoo/wow/cache/QueryServiceCacheSourceTest.kt
- Add new interfaces and classes for more flexible cache source implementation
- Introduce LoadCacheSourceConfiguration for configurable loading behavior
- Update dependencies to include wow-query module
- Add unit tests for QueryServiceCacheSource
> refactor(cocache): introduce StateCacheSource and QueryServiceCacheSource

- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/AbstractCommandFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/SimpleCommandAggregate.kt
- Move function and event stream setting in AbstractCommandFunction
- Remove duplicate logic from SimpleCommandAggregate
- Improve code organization and reduce redundancy
> refactor(wow-core): optimize command processing and event stream handling

- wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/SetStateCacheRefresher.kt
- Introduce open evict method for better code organization
- Improve readability and maintainability of refresh method
> refactor(cache): optimize SetStateCacheRefresher with evict method

- documentation/docs/guide/getting-started.md
- Update the project template zip file link from v5.5.5 to v5.6.5 in the getting started guide
> docs(guide): update project template version in getting started guide

- wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- Extract error mapping logic to a reusable extension function
- Implement sendAndWaitForSent function in DefaultCommandGateway
- Remove redundant code and improve code readability
> refactor(wow-core): improve error handling in CommandGateway

- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- Add a warning log when the wait strategy is cancelled or terminated
- Improve visibility and debugging for command gateway operations
> chore(core): add log for cancelled or terminated wait strategy

- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- Add ensureUnregister extension function to Mono<Void> for command cancellation handling
- Introduce proper cancellation and error handling for sent commands
> fix(wow-core): ensure command cancellation is properly handled

- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/Responses.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandler.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/handler/CommandHandlerTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/ResponsesKtTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/DefaultCommandMessageParserTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/appender/CommandRequestExtendHeaderAppenderTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/appender/CommandRequestRemoteIpHeaderAppenderTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/appender/CommandRequestUserAgentHeaderAppenderTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/compensation/EventCompensateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/event/ListQueryEventStreamHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/event/LoadEventStreamHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/id/GlobalIdHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/metadata/GetWowMetadataHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/BatchRegenerateSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/CountSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/ListQuerySnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/ListQuerySnapshotStateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/LoadSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/PagedQuerySnapshotHandlerFunctionFactoryTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/PagedQuerySnapshotStateHandlerFunctionFactoryTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/RegenerateSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotStateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/AggregateTracingHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadAggregateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadTimeBasedAggregateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadVersionedAggregateHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/OwnerAggregatePreconditionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/ResendStateEventHandlerFunctionTest.kt
- Add timeout exception handling for command requests
- Modify SSE data type to String and handle errors
- Update responses to include error codes and improve error handling
- Refactor test cases for better coverage
> fix(webflux): handle command request timeout and improve SSE response

- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/Responses.kt
- Remove unused imports
- Enhance error handling to use common errorInfo across different error scenarios
- Refactor timeout error handling to use generic errorInfo
- Add global error handling for serverSentEventStream
> refactor(webflux): improve error handling in Responses

- wow-core/src/main/kotlin/me/ahoo/wow/exception/WowException.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/CommandValidationExceptionTest.kt
- Update CommandValidationExceptionTest to reflect changes in error message format
- Refactor WowException to use lazy initialization for errorMsg property
- Remove unnecessary binding error formatting in favor of a simpler message
> feat(exception): improve error message handling in WowException

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/IgnoreCommandRouteVariableCheck.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/JsonSchemaGenerator.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinCustomDefinitionProvider.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinNullableCheck.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinReadOnlyCheck.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinRequiredCheck.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinWriteOnlyCheck.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- Add nullable check for Kotlin properties
- Add read-only check for Kotlin properties
- Add required check for Kotlin properties
- Add write-only check for Kotlin properties
- Implement custom definition provider for Kotlin
- Update JSON schema generator to support Kotlin
> feat(schema): add Kotlin schema support

- compensation/wow-compensation-server/src/main/kotlin/me/ahoo/wow/compensation/server/webhook/weixin/WeiXinWebHook.kt
- Update annotation from @StatelessSaga to @EventProcessor for WeiXinWebHook class
- This change is part of a larger refactor to improve clarity and consistency in the codebase
> refactor(compensation): rename StatelessSaga to EventProcessor

- documentation/docs/guide/projection.md
- documentation/docs/guide/saga.md
- Change @ProjectionProcessor to @ProjectionProcessorComponent in projection example
- Change @StatelessSaga to @StatelessSagaComponent in saga example
> docs(guide): update projection and saga annotations

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/JsonSchemaGenerator.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowOption.kt
- Add default parameter to JsonSchemaGenerator and WowModule constructors
- Create ALL constant in WowOption companion object
- Simplify option handling and improve code readability
> refactor(schema): set default options for JsonSchemaGenerator and WowModule

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaDefinitionNamingStrategy.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinCustomDefinitionProvider.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaDefinitionNamingStrategyTest.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Improve schema naming strategy to handle nested and complex types
- Add support for naming schemas with type parameters and arrays
- Refactor type resolution and schema name generation for better readability
- Update tests to cover new schema naming scenarios
> feat(schema): enhance schema naming strategy and support complex types

- wow-schema/build.gradle.kts
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Update OpenAPISchemaBuilderTest:
- Add test for String schema generation
- Improve test coverage for CreateOrder and AddCartItem schemas
- Refine build.gradle.kts:
- Update project description from "Wow Model Context Protocol" to "Wow Schema"
> test(wow-schema): update OpenAPISchemaBuilderTest and refine build.gradle.kts

- .idea/modules.xml
- .idea/modules/wow-apiclient/Wow.wow-apiclient.main.iml
- wow-apiclient/src/main/resources/META-INF/wow-metadata.json
- Create wow-metadata.json file in wow-apiclient module
- Define context for wow.apiclient with scope "me.ahoo.wow.apiclient"
> feat(wow-apiclient): add metadata for wow-apiclient context

- example/example-server/src/main/resources/application.yaml
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- Filter out path parameters based on routing strategy
- Improve logic for handling ID, OWNER_ID, and TENANT_ID path variables
- Enhance readability and maintainability of path parameter generation
> fix(openapi): optimize path parameters handling for command routes 

- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/MockPathCommand.kt
- example/example-domain/src/main/kotlin/me/ahoo/wow/example/domain/cart/Cart.kt
- Add MockPathCommand class to handle mock path requests
- Update Cart class to include MockPathCommand in its aggregate root
> feat(example): add mock path command to cart aggregate

- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/BatchResults.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/global/GenerateBIScriptHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/global/GetWowMetadataHandlerFunction.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/global/GlobalIdHandlerFunction.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/bi/GenerateBIScriptHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/id/GlobalIdHandlerFunctionTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/metadata/GetWowMetadataHandlerFunctionTest.kt
- Replace logback with KotlinLogging for better performance
- Refactor package structure for global functions
- Update related test files to match new package structure
- Consolidate imports in WebFluxAutoConfiguration
> refactor(wow-webflux): update logging and reorganize packages

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/context/OpenAPIComponentContext.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Remove unnecessary companion objects
- Convert DefaultCustomizer and InlineCustomizer to objects
- Update import statements
- Adjust JakartaValidationModule initialization
> refactor(schema): optimize OpenAPISchemaBuilder and related classes

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregatedDomainEventStreamDefinitionProvider.kt
- Refactor event schema generation logic for better maintainability
- Introduce metadata integration to support additional event types
- Improve type resolution and schema creation for event types
- Optimize event metadata handling and sorting
> feat(schema): enhance event schema generation and metadata integration

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt
- Add descriptions to tenantId, ownerId, aggregateVersion, and other parameters
- Reorder functions for better organization
- Remove duplicate code and consolidate related functions
- Improve readability and maintainability of the CommandComponent class
> refactor(wow-openapi): enhance command header parameters and reorganize code structure

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt
- Update localFirst header parameter schema from StringSchema to BooleanSchema
- Add description for the localFirst header parameter
> feat(wow-openapi): add description for localFirst header parameter

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandFacadeRouteSpec.kt
- Update summary to "Unified sending endpoint for command messages"
- Change request body description to "command message body"
> docs(wow-openapi): update command facade route documentation

- wow-api/src/main/kotlin/me/ahoo/wow/api/naming/SummaryCapable.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadata.kt
- Add SummaryCapable interface in wow-api for consistent summary representation
- Implement SummaryCapable in CommandRouteMetadata for better summary management
- Update RouteSpec to inherit SummaryCapable for unified interface
> refactor(api): introduce SummaryCapable interface for consistent summary handling

- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/AddCartItem.kt
- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/ChangeAddress.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregatedDomainEventStreamDefinitionProvider.kt
- wow-schema/src/test/resources/META-INF/wow-schema/CartAggregatedDomainEventStream.json
- Add @Summary annotation to API response classes
- Update JSON schema generation to use @Summary annotation
- Improve API documentation readability with concise response descriptions
> feat(api): add summary annotation for API Schema

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/state/StateAggregateFactorySpec.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/state/SimpleStateAggregateTest.kt
- Add unit test for ConstructorStateAggregateFactory.toStateAggregate method
- Update related test files to improve test coverage
- Refactor some test code to improve readability and maintainability
> test(modeling): add unit test for ConstructorStateAggregateFactory

- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/Description.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/naming/DescriptionCapable.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadata.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadataParser.kt
- Add Description annotation to support command description
- Update CommandRouteMetadata to include description
- Modify CommandRouteMetadataParser to parse description
- Add DescriptionCapable interface for description support
- Update RouteSpec to include description
> feat(api): add description support for command route

- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/Description.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/DescriptionResolver.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/SummaryTitleResolver.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- Add @Summary and @Description annotations support for fields
- Implement SummaryTitleResolver and DescriptionResolver for JSON schema generation
- Update WowModule to use new resolvers
- Add deprecation warning for summary and description in CommandRoute
> feat(api): add summary and description annotations for fields

- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/MockPathCommand.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- Add variableSchema() function to generate schema based on variable type
- Update path and header parameters to use the new schema function
- Add enum example in MockPathCommand
> feat(openapi): support enum and integer path variables

- codecov.yml
- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/MockVariableCommand.kt
- example/example-domain/src/main/kotlin/me/ahoo/wow/example/domain/cart/Cart.kt
- Rename MockPathCommand to MockVariableCommand in Cart aggregate
- Update codecov.yml to exclude additional directories
- Modify MockVariableCommand to include header parameters
> refactor(example): update command handling and coverage configuration

- wow-api/src/main/kotlin/me/ahoo/wow/api/query/Condition.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/query/DeletionState.kt
- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/query/AbstractElasticsearchConditionConverter.kt
- wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/query/event/EventStreamConditionConverter.kt
- wow-elasticsearch/src/test/kotlin/me/ahoo/wow/elasticsearch/query/ElasticsearchConditionConverterTest.kt
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/AbstractMongoConditionConverter.kt
- wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/event/EventStreamConditionConverter.kt
- wow-mongo/src/test/kotlin/me/ahoo/wow/mongo/query/SnapshotConditionConverterTest.kt
- wow-query/src/main/kotlin/me/ahoo/wow/query/converter/AbstractConditionConverter.kt
- wow-query/src/main/kotlin/me/ahoo/wow/query/dsl/ConditionDsl.kt
- wow-query/src/main/kotlin/me/ahoo/wow/query/snapshot/filter/MaskingSnapshotQueryFilter.kt
- wow-query/src/main/kotlin/me/ahoo/wow/query/snapshot/filter/SnapshotQueryFilter.kt
- wow-query/src/test/kotlin/me/ahoo/wow/query/dsl/ConditionDslTest.kt
- Add DeletionState enum to represent active, deleted, and all states
- Update Condition class to support DeletionState
- Refactor AbstractConditionConverter to handle deletion state more efficiently
- Modify Elasticsearch and MongoDB converters to support new deletion state logic
- Simplify ConditionConverter interface
> feat(query): optimize deletion state handling and condition conversion

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinIgnoreCheck.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinModule.kt
- Refactor KotlinIgnoreCheck to support both FieldScope and MethodScope
- Introduce KotlinFieldIgnoreCheck and KotlinMethodIgnoreCheck for specific use cases
- Update KotlinModule to use separate ignore checks for fields and methods
> feat(schema): improve Kotlin ignore check for methods

- documentation/docs/guide/test-suite.md
- Replace OrderTest with CartTest to focus on Cart aggregate
- Add tests for addCartItem, removeCartItem, and changeQuantity
- Update onOrderCreated test to use CartTest context
- Remove unnecessary comments and refactor test structure
> test(documentation): update test suite guide with Cart aggregate tests

- documentation/docs/guide/getting-started.md
Updated the download link for the project template from version 5.11.0 to 5.11.2.
> docs(guide): update project template download link to v5.11.2

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategy.kt
- Replaced reverse for loop with forEach for better readability.
- No functional changes, only code style improvement.
> refactor(wow-schema): Simplify type parameter iteration in WowSchemaNamingStrategy

- wow-core/src/test/kotlin/me/ahoo/wow/modeling/NamedAggregateTest.kt
- Add test cases for hashCode comparison
- Include tests for materialize function with different scenarios
- Implement tests for toNamedAggregate function with various inputs
- Add tests for getContextAliasPrefix function
- Include test for toNamedAggregateString function
- Remove existing test case for materialize function
> test(wow-core): improve NamedAggregateTest with new test cases

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/naming/WowSchemaNamingStrategy.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
- Add support for naming non-static inner classes
- Handle static nested classes in a consistent manner
- Update unit tests to cover new naming scenarios
> fix(schema): improve schema naming for nested and inner classes

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/naming/WowSchemaNamingStrategy.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
- Add constant for array schema name
- Enhance class naming to include enclosing class for member classes
- Refactor type flattening to remove redundant enclosing class addition
- Update tests to reflect new naming strategy for nested classes
> fix(schema): improve naming strategy for member classes and arrays

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt
- Move inline and componentContext properties
- Adjust class inheritance and interface implementations
> refactor(wow-openapi): reorganize RouterSpecs class structure

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/RouterFunctionBuilder.kt
- Remove unnecessary check for empty router specs in RouterFunctionBuilder
- Update RouterSpecs class to implement Iterable instead of MutableList
- Replace direct add() calls with routes.add() to maintain encapsulation
> refactor(openapi): optimize route specs handling and remove redundant code

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/messaging/MessageBusSpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/compensation/CompensationMatcher.kt
- Add isCompensation property to Header class for checking if it's a compensation message
- Update match function to use the new isCompensation property
> feat(wow-core): add isCompensation property to Header

- wow-api/src/main/kotlin/me/ahoo/wow/api/Copyable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Header.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/TopicKind.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/AggregateId.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/AggregateIdCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/NamedAggregate.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/OwnerId.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/TenantId.kt
- wow-core/src/main/kotlin/me/ahoo/wow/filter/ErrorAccessor.kt
- wow-core/src/main/kotlin/me/ahoo/wow/filter/Filter.kt
- wow-core/src/main/kotlin/me/ahoo/wow/filter/FilterChainBuilder.kt
- wow-core/src/main/kotlin/me/ahoo/wow/filter/Handler.kt
- wow-core/src/main/kotlin/me/ahoo/wow/id/AggregateIdGeneratorFactory.kt
- wow-core/src/main/kotlin/me/ahoo/wow/id/GlobalIdGeneratorFactory.kt
- Added comprehensive Kotlin doc comments to AggregateIdGeneratorFactory, ErrorAccessor, Filter, FilterChainBuilder, GlobalIdGeneratorFactory, Handler, and ErrorHandler
- Clarified the purpose and usage of these interfaces and classes
- Provided detailed explanations for methods and properties
- Improved code readability and maintainability
> refactor(wow-core): add Kotlin doc comments to key interfaces and classes

- gradle/libs.versions.toml
- wow-dependencies/build.gradle.kts
- Add springdoc-bom platform dependency
- Remove individual springdoc dependencies
> build(deps): Add springdoc-bom platform dependency

- README.md
- README.zh-CN.md
- Added DeepWiki badge to both README.md and README.zh-CN.md
- The badge links to the DeepWiki page for the Wow project
> docs(badge): add DeepWiki badge to README files

- wow-models/src/main/kotlin/me/ahoo/wow/models/common/CompletedCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/ItemIdCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/QuantityCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/ReasonCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/RemarkCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/TypeCapable.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/CompletedCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/ItemIdCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/QuantityCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/ReasonCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/RemarkCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/TypeCapableTest.kt
- Add CompletedCapable interface for tracking completion status
- Add QuantityCapable interface for managing quantities
- Add ReasonCapable interface for storing reasons
- Add RemarkCapable interface for adding remarks
- Add TypeCapable interface for defining types
- Implement unit tests for all new interfaces
> feat(models): add common interfaces and tests for various capabilities

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/MessageDefinitionProvider.kt
- wow-schema/src/main/resources/META-INF/wow-schema/AggregateId.json
- wow-schema/src/main/resources/META-INF/wow-schema/AggregatedDomainEventStream.json
- wow-schema/src/main/resources/META-INF/wow-schema/CommandMessage.json
- wow-schema/src/main/resources/META-INF/wow-schema/CurrencyUnit.json
- wow-schema/src/main/resources/META-INF/wow-schema/DomainEvent.json
- wow-schema/src/main/resources/META-INF/wow-schema/DomainEventStream.json
- wow-schema/src/main/resources/META-INF/wow-schema/Money.json
- wow-schema/src/main/resources/META-INF/wow-schema/Snapshot.json
- wow-schema/src/main/resources/META-INF/wow-schema/StateAggregate.json
- wow-schema/src/main/resources/META-INF/wow-schema/StateEvent.json
- wow-schema/src/test/resources/META-INF/wow-schema/CartAggregatedDomainEventStream.json
- wow-schema/src/test/resources/META-INF/wow-schema/EmptyAggregatedDomainEventStream.json
- Removed "title" attribute from multiple JSON schema files
- Updated MessageDefinitionProvider to remove "title" attribute from typed schema
> refactor(schema): remove title attribute from JSON schemas

- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/GlobalExceptionHandler.kt
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/RequestExceptionHandler.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/DefaultRequestExceptionHandlerTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/GlobalExceptionHandlerTest.kt
- Add handling for ServerWebInputException in GlobalExceptionHandler
- Implement toInputErrorInfo() extension function for ServerWebInputException
- Update RequestExceptionHandler to handle ServerWebInputException
- Add unit tests for ServerWebInputException handling
> fix(exception): handle ServerWebInputException

- wow-webflux/build.gradle.kts
- wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/HandlerMethodValidationExceptionConverter.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/GlobalExceptionHandlerTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/HandlerMethodValidationExceptionConverterTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/NoResourceFoundExceptionConverterTest.kt
- wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/ServerWebInputExceptionConverterTest.kt
- Removed redundant test cases
- Created new test classes for specific exception types
- Improved test structure for easier maintenance
- Added unit tests for exception converters
> test(wow-webflux): refactoring test cases for better maintainability

- wow-api/src/main/kotlin/me/ahoo/wow/api/query/Condition.kt
- Add ICondition interface with properties common to all conditions
- Make Condition data class implement ICondition interface
- This change allows for more flexible condition handling and potential future extensions
> refactor(api): introduce ICondition interface

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/AggregatedFieldPaths.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregatedFieldsDefinitionProvider.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/AggregatedFieldPathsTest.kt
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedFields.json
- Rename StateFieldPaths to AggregatedFieldPaths
- Add support for nested collection and array fields
- Implement depth limit for field path resolution
- Update related tests and implementations
> feat(schema): rename and enhance field path resolution

- wow-api/src/main/kotlin/me/ahoo/wow/api/query/Condition.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/ListQuerySnapshotRouteSpec.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AbstractAggregatedQueryDefinitionProvider.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedListQuery.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedListQueryDefinitionProvider.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/QueryDefinitionProvider.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedListQuery.json
- Implement AggregatedListQuery interface for querying aggregated data
- Create AggregatedListQueryDefinitionProvider to handle schema generation
- Update AggregatedCondition to use generic type parameter
- Modify ListQuerySnapshotRouteSpec to use aggregated list query
- Add new JSON schema for OrderAggregatedListQuery
> feat(schema): add support for AggregatedListQuery in JSON schema generation

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/SingleSnapshotRouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/SingleSnapshotStateRouteSpec.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedConditionCapableDefinitionProvider.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedSingleQuery.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedSingleQuery.json
- Implement AggregatedSingleQuery interface and related definitions
- Update QueryComponent to handle single query request body
- Modify SingleSnapshotRouteSpec and SingleSnapshotStateRouteSpec to use aggregated single query
- Add AggregatedSingleQueryDefinitionProvider to WowModule
> feat(schema): add support for SingleQuery in aggregated queries

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt
- Update schema assignments for list and paged queries
- Correctly assign AggregatedListQuery and AggregatedPagedQuery classes
> fix(wow-openapi): fix query component schema assignments

- documentation/docs/guide/test-suite.md
- Align event type expectations in test scenarios for consistency
- Improve readability and maintainability of test examples in the guide
> docs(guide): update test-suite.md with consistent event type expectations

- wow-schema/src/main/kotlin/me/ahoo/wow/schema/JavaTypeResolver.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JavaTypeResolverTest.kt
- Implement JavaTypeResolver object with toResolvedType extension function for JavaType
- Add unit tests for JavaTypeResolver to ensure correct conversion
> feat(schema): add JavaType to ResolvedType conversion utility

- wow-openapi/build.gradle.kts
- wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/converter/ModelConvertersTest.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/JavaTypeResolver.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinCustomDefinitionProvider.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Add caching mechanism in JavaTypeResolver and KotlinCustomDefinitionProvider
- Prevent infinite recursion when resolving types with circular references
- Improve performance for complex data structures
> perf(schema): optimize recursive data structure handling

- example/example-server/build.gradle.kts
- Add spring-cloud-starter-loadbalancer to the implementation dependencies
> build(example-server): add spring cloud loadbalancer dependency

- wow-core/src/main/kotlin/me/ahoo/wow/exception/ErrorConverterRegistrar.kt
- wow-core/src/test/kotlin/me/ahoo/wow/exception/ErrorConverterRegistrarTest.kt
- Add factory registration method to ErrorConverterRegistrar
- Implement return values for register and unregister methods
- Update unit tests to cover new functionality
- Improve test assertions for better code verification
> feat(exception): enhance ErrorConverterRegistrar with factory registration and improve test coverage

- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/MaterializeState.kt
- Define MaterializeState interface with a generic type MATERIALIZED
- Add materialize() function to the interface
- This change allows for a standardized way to materialize objects in the API
> interface(MaterializeState): add materialize interface

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/Tags.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/AggregateRouteSpec.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/TagsTest.kt
- Update tag properties to use io.swagger.v3.oas.models.tags.Tag instead of String
- Enhance tag generation from annotations using AnnotationsUtils- Add unit tests for tag conversion from single and multiple annotations
- Integrate tag addition in RouterSpecs
> feat(openapi): improve tag handling and integration

- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/DeletedCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/EventTimeCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/FirstEventTimeCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/FirstOperatorCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/OperatorCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/StateCapable.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/query/MaterializedSnapshot.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/query/SlimMaterializedSnapshot.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/ReadOnlyStateAggregate.kt
- Add DeletedCapable, EventTimeCapable, FirstEventTimeCapable, FirstOperatorCapable, OperatorCapable, and StateCapable interfaces
- Implement these interfaces in MaterializedSnapshot and ReadOnlyStateAggregate
- Create SlimMaterializedSnapshot class for simplified snapshot representation
- Update related files to use new modeling interfaces
> refactor(api): introduce common modeling interfaces and simplify snapshots

- wow-api/src/main/kotlin/me/ahoo/wow/api/Version.kt
- Add Schema annotations to Version class properties
- Hide initialized and isInitialVersion fields from Swagger UI
> feat(api): add swagger schema annotation for Version

- wow-core/build.gradle.kts
- wow-core/src/main/kotlin/me/ahoo/wow/ioc/ServiceProvider.kt
- wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt
- wow-core/src/test/kotlin/me/ahoo/wow/ioc/SimpleServiceProviderTest.kt
- wow-spring/src/main/kotlin/me/ahoo/wow/spring/SpringServiceProvider.kt
- Add KType parameter overloads to ServiceProvider interface
- Implement KType-based service registration and retrieval in SimpleServiceProvider
- Add KType support in SpringServiceProvider
- Update build.gradle.kts to include kotlin-reflect dependency
> feat(core): add support for Kotlin types in ServiceProvider

- wow-core/src/main/kotlin/me/ahoo/wow/command/annotation/CommandMetadataParser.kt
- Remove unused import of KotlinLogging
- Delete unused logger companion object
- Eliminate unnecessary null check and warning log for aggregate ID
> refactor(command): remove unused logging and improve code clarity

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/ApiResponseBuilder.kt
- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt
- Rename parameters in ApiResponseBuilder for better clarity
- Update usage of renamed parameters in CommandComponent
> refactor(wow-openapi): improve ApiResponseBuilder and CommandComponent

- wow-schema/build.gradle.kts
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/JsonSchemaGenerator.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/web/ServerSentEvent.kt
- wow-schema/src/main/kotlin/me/ahoo/wow/schema/web/ServerSentEventCustomDefinitionProvider.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaTest.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/web/ServerSentEventTest.kt
- Add custom definition provider for ServerSentEvent
- Update JsonSchemaGenerator to include new module
- Add tests for ServerSentEvent schema generation
- Refactor JsonSchemaGenerator to use ObjectMapperFactory
- Update dependencies, including spring-web
> feat(schema): add support for Spring Web ServerSentEvent

- compensation/wow-compensation-dashboard/src/app/apply-retry-spec/apply-retry-spec.component.ts
- compensation/wow-compensation-dashboard/src/app/failed-list/failed-list.component.ts
- Remove unnecessary ngOnInit lifecycle
- Simplify class definition and form initialization
- Improve code readability and maintainability
> refactor(compensation): simplify ApplyRetrySpecComponent

- schema/query/definitions.schema.json
- schema/query/list-query.schema.json
- schema/query/paged-query.schema.json
- schema/query/single-query.schema.json
- schema/wow-metadata.schema.json
- Update wow-metadata.schema.json to draft-07
- Update definitions.schema.json to draft-07
- Update list-query.schema.json to draft-07
- Update paged-query.schema.json to draft-07
- Update single-query.schema.json to draft-07
> build(schema): update JSON schema draft version to 07

- example/example-api/src/main/kotlin/me/ahoo/wow/example/api/ExampleService.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/BoundedContext.kt
- wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/metadata/BoundedContextResolver.kt
- wow-core/src/main/kotlin/me/ahoo/wow/configuration/WowMetadata.kt
- wow-core/src/test/kotlin/me/ahoo/wow/configuration/BoundedContextTest.kt
- Add description property to BoundedContext annotation and class
- Implement DescriptionCapable interface for BoundedContext
- Update BoundedContextResolver to handle new description property
- Add tests for merging BoundedContext with description
- Update ExampleService to demonstrate usage of description property
> feat(BoundedContext): add description property and implement DescriptionCapable

- .idea/modules.xml
- example/example-server/build.gradle.kts
- wow-spring-boot-starter/build.gradle.kts
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/cosec/CoSecAutoConfiguration.kt
- wow-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/cosec/CoSecAutoConfigurationTest.kt
- Create CoSecAutoConfiguration class to automatically configure CoSecCommandRequestHeaderAppender
- Add conditional annotations to enable configuration only when required classes are present
- This change enables seamless integration of CoSec with the Spring Boot application
> feat(wow-spring-boot-starter): add CoSec auto configuration

- wow-api/src/main/kotlin/me/ahoo/wow/api/messaging/Message.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/CreateTimeCapable.kt
- Add CreateTimeCapable interface for classes with creation time
- Extend Message interface with CreateTimeCapable
- Add detailed comments and improve method descriptions in Message interface
- Introduce NamedBoundedContextMessage and NamedMessage interfaces
> feat(api): add CreateTimeCapable interface and enhance Message interface

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/DomainEventBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/DomainEventStreamSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/StateAggregateRepositorySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotRepositorySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/snapshot/SnapshotStrategySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/state/StateEventBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/messaging/MessageBusSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/command/CommandDispatcherSpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/state/StateAggregateFactorySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/prepare/PrepareKeySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/projection/ProjectionDispatcherSpec.kt
- test/wow-tck/src/main/resources/META-INF/wow-metadata.json
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/annotation/StateAggregateMetadataParser.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/matedata/StateAggregateMetadata.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/StateAggregateFactory.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/annotation/AggregateMetadataParserTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/annotation/MockAggregates.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/matedata/AggregateMetadataTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/matedata/CommandAggregateMetadataTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/matedata/SimpleNamedAggregateGetterTest.kt
- wow-core/src/test/kotlin/me/ahoo/wow/modeling/state/StateAggregatesTest.kt
- wow-core/src/test/resources/META-INF/wow-metadata.json
- Update StateAggregateFactory to support multiple constructor patterns
- Modify StateAggregateMetadata to allow optional aggregateIdAccessor
- Improve error messages and constructor parsing in StateAggregateMetadataParser
> feat(core): enhance StateAggregate instantiation and metadata handling

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/matedata/AggregateMetadata.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/StateAggregateFactory.kt
- Add extractAggregateId function to AggregateMetadata
- Update StateAggregateFactory to use the new extractAggregateId method
- Modify DefaultAggregateVerifier to use aggregateId and tenantId parameters
- Remove redundant aggregateId calculations in tests
> feat(modeling): improve aggregate ID handling in metadata

- wow-api/src/main/kotlin/me/ahoo/wow/api/query/MaterializedSnapshot.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/query/MediumMaterializedSnapshot.kt
- wow-api/src/main/kotlin/me/ahoo/wow/api/query/SmallMaterializedSnapshot.kt
- Update IMaterializedSnapshot to include withState method
- Implement withState in MaterializedSnapshot, MediumMaterializedSnapshot, and SmallMaterializedSnapshot
- Refactor interface to use SOURCE type parameter for self-referential types
> feat(api): enhance IMaterializedSnapshot with withState method

- wow-api/src/main/kotlin/me/ahoo/wow/api/Version.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaTest.kt
- Add JsonSchema test for SmallMaterializedSnapshot class
- Remove @Schema annotations from Version class properties
- Update Version class by adding @JsonIgnore annotation to specific properties
> feat(wow-api): Remove @Schema annotations from Version class properties

- .gitignore
- Ignore .DS_Store files
- Ignore .vscode directory
- Ignore jte-classes directory
- Ignore .kotlin directory
> chore: add additional ignore rules to .gitignore

- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForAfterProcessed.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForEventHandled.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForProjected.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForSagaHandled.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForSent.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForStage.kt
- Introduce WaitingForFunction and WaitingForStage abstract classes
- Update existing waiting classes to inherit from new abstract classes
- Simplify isWaitingForSignal logic in WaitingForFunction
- Remove redundant code and improve overall structure
> refactor(wow-core): optimize wait mechanism and simplify waiting conditions

- wow-models/src/main/kotlin/me/ahoo/wow/models/common/ReasonCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/RemarkCapable.kt
- wow-models/src/main/kotlin/me/ahoo/wow/models/common/TitleCapable.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/ReasonCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/RemarkCapableTest.kt
- wow-models/src/test/kotlin/me/ahoo/wow/models/common/TitleCapableTest.kt
- Introduce NullableReasonCapable, NullableRemarkCapable, and NullableTitleCapable interfaces
- Update ReasonCapable, RemarkCapable, and TitleCapable to extend nullable interfaces
- Add tests for nullable capabilities
> refactor(models): add nullable capabilities for reason, remark, and title

- wow-api/src/main/kotlin/me/ahoo/wow/api/exception/ErrorInfo.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/CommandExchange.kt
- Simplify error detection in DomainEvent stream
- Add isFailed extension function to ErrorInfo
- Reduce boilerplate code in error checking
> refactor(wow-core): improve error handling in CommandExchange

- wow-core/src/main/kotlin/me/ahoo/wow/command/CommandExceptions.kt
- wow-core/src/main/kotlin/me/ahoo/wow/exception/NotFoundResourceException.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandAggregateExceptions.kt
- wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/SourcingVersionConflictException.kt
- wow-core/src/test/kotlin/me/ahoo/wow/exception/NotFoundResourceExceptionTest.kt
- Add `cause` parameter to `CommandAggregateExceptions`, `CommandValidationException`, and `NotFoundResourceException`
- Update error messages in `CommandAggregateExceptions` and `SourcingVersionConflictException`
- Add tests for `throwNotFoundIfNull` extension function
> refactor(exception): enhance exception handling with cause and improve error messages

- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfiguration.kt
- wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfigurationTest.kt
- Implement PrepareKeyProxyFactory bean creation in PrepareAutoConfiguration
- Add unit test to verify PrepareKeyProxyFactory bean existence
> feat(prepare): add PrepareKeyProxyFactory bean

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt
- Replace require() with more specific AssertionError messages
- Add checks for both unexpected errors and missing expected errors
- Enhance error handling to provide clearer feedback in tests
> test(wow-test): improve error verification in VerifiedStage

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/CommandIterator.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/ExpectStage.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/ExpectedResult.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/WhenStage.kt
- Move CommandIterator to new file: CommandIterator.kt- Create new file for ExpectedResult: ExpectedResult.kt
- Extract ExpectStage interface to new file: ExpectStage.kt
- Create new file for WhenStage interface: WhenStage.kt
- Remove original Stages.kt file
> refactor(wow-test): split Stages.kt into separate files for better maintainability

- documentation/docs/guide/test-suite.md
- Refactor CartTest to CartSpec using AggregateSpec
- Refactor CartSagaTest to CartSagaSpec using SagaSpec
- Consolidate test scenarios and remove redundant tests
- Improve test readability and maintainability
> refactor(test-suite): update Cart and CartSaga test cases

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/AggregateExpecter.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt
- Simplify class name references in test descriptions
- Enhance type safety and reduce boilerplate in expect methods
- Refactor expectEventType to handle both KClass and Class types
- Update expectErrorType to use Kotlin's reified type parameters
- Standardize dynamic test naming conventions
> refactor(test): improve readability and maintainability of aggregate testing DSL

- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/StatelessSagaExpecter.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt
- Remove redundant function overrides in DefaultStatelessSagaDsl
- Improve type handling in StatelessSagaExpecter
- Simplify expectCommandType and expectErrorType functions
> refactor(test): optimize expect DSL for stateless saga

- wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt
- Replace send() with sendAndWaitForSent() in command processing
- This change improves the reliability of command execution
> refactor(wow-core): update command handling in StatelessSagaFunction

- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategyInfo.kt
- Add Materialized interface implementation to WaitStrategyInfo
- This change enhances the capabilities of WaitStrategyInfo by integrating materialization functionality
> feat(WaitStrategyInfo): implement Materialized interface

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/DefaultCommandGatewayTest.kt
- Extract commandSentSignal function to simplify signal creation
- Improve error handling by using onErrorResume
- Remove redundant code and refactor for better readability
- Update tests to accommodate new behavior
> refactor(command): optimize command sending and error handling

- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt
- test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/command/CommandDispatcherSpec.kt
- test/wow-test/src/main/kotlin/me/ahoo/wow/test/SagaVerifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- wow-core/src/test/kotlin/me/ahoo/wow/command/DefaultCommandGatewayTest.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandGatewayAutoConfiguration.kt
- wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt
- Add CommandWaitNotifier to send wait signals for commands
- Integrate LocalCommandWaitNotifier in various components
- Update DefaultCommandGateway to handle wait strategy and send wait signals
- Modify CommandGatewayAutoConfiguration to include commandWaitNotifier
> feat(command): add command wait notification

- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt
- Add CompletedCapable interface to WaitStrategy
- Override completed property to use existing logic
- This change allows WaitStrategy to integrate with components that require CompletedCapable functionality
> feat(WaitStrategy): implement CompletedCapable interface

- wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/ExtractedWaitStrategy.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForFunction.kt
- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagator.kt
- wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagatorTest.kt
- Simplify command wait ID propagation logic
- Enhance WaitStrategy interface with shouldPropagate method
- Refactor WaitStrategyPropagator to better handle message propagation- Update command wait notifier and related classes to use new logic
- Add unit tests for new command wait propagation behavior
> refactor(wow-core): optimize command wait strategy and propagation

- wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt
- Change tryEmit method visibility from private to protected
> refactor(wow-core): update tryEmit method visibility

- wow-core/src/test/kotlin/me/ahoo/wow/command/wait/chain/SimpleWaitingChainTest.kt
- Add test for propagating CommandMessage upstream
- Add test for propagating DomainEvent upstream
- Verify correct extraction and casting of SimpleWaitingChain
> test(wow-core): add tests for SimpleWaitingChain propagation

- example/example-server/src/dist/config/application.yaml
- Add management endpoints and health probes
- Configure Springdoc for API documentation
- Exclude Elasticsearch autoconfiguration
- Add MongoDB connection URI
- Remove Redis autoconfiguration
- Update logging level to debug
- Add Kafka bootstrap servers
- Comment out R2DBC configuration
> build(example-server): update application configuration

- .idea/kotlinc.xml
- compensation/dashboard/package.json
- compensation/dashboard/pnpm-lock.yaml
- Update @ahoo-wang/fetcher and related packages from 1.5.6 to 1.5.8
- Update Kotlin plugin version from 2.2.10 to 2.2.20
> build(deps): update fetcher dependencies to v1.5.8

- compensation/dashboard/package.json
- compensation/dashboard/pnpm-lock.yaml
- Update @ahoo-wang/fetcher from 1.5.8 to1.5.9
- Update @ahoo-wang/fetcher-decorator from 1.5.8 to 1.5.9
- Update @ahoo-wang/fetcher-eventstream from 1.5.8 to 1.5.9
- Update @ahoo-wang/fetcher-wow from 1.5.8 to 1.5.9
> build(compensation-dashboard): update @ahoo-wang/fetcher packages to v1.5.9

- compensation/dashboard/package.json
- compensation/dashboard/pnpm-lock.yaml
- compensation/dashboard/src/services/cosec.ts
- Add cosec request interceptor to compensation fetcher
- Implement cosec functionality for app security
- Update package dependencies to include fetcher-cosec
> feat(compensation): integrate cosec request interceptor

- compensation/dashboard/src/features/Failed/FailedView.tsx
- Add useCallback hooks to prevent unnecessary re-renders
- Refactor search function to use useCallback and update useEffect dependency
- Improve overall component performance and user experience
> perf(compensation): optimize FailedView component performance

- compensation/wow-compensation-server/src/main/resources/application.yaml
- Add server.compression.enabled: true to application.yaml
- This change will improve performance by compressing HTTP responses
> perf(server): enable HTTP response compression

- wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/metadata/CommandAggregateRootResolver.kt
- wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedListQuery.json
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedPagedQuery.json
- wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedSingleQuery.json
- Add package scope information to the Aggregate object in the CommandAggregateRootResolver
- This enhancement improves the metadata resolution for aggregate roots
> feat(compiler): add package scope to aggregate root metadata

- wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/event/EventComponent.kt
- Update compensation target response content type from TEXT_PLAIN to APPLICATION_JSON
- Maintain integer schema for compensation count
- Ensure proper error code header handling in response
> fix(openapi): change event compensation response to JSON

- example/example-server/src/main/kotlin/me/ahoo/wow/example/server/cart/CartController.kt
- example/example-server/src/main/kotlin/me/ahoo/wow/example/server/order/OrderQueryController.kt
- Added @Tag annotation to CartController with name "Cart" and description
- Added @Tag annotation to OrderQueryController with name "Order" and description
- Imported io.swagger.v3.oas.annotations.tags.Tag in both controller files
> docs(api): add Swagger tags for Cart and Order controllers
