Ahoo-Wang/Wow

gradle.properties, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/MockEvent.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/StatelessSagaVerifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotRepository.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/modeling/AggregateAutoConfigurationTest.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfigurationTest.kt
- refactor: remove Deprecated `SnapshotRepository.load`
=> refactor: remove Deprecated `SnapshotRepository.load`

gradle.properties, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventStore.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/MongoEventStore.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/handler/RegenerateStateEventHandler.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/BatchRegenerateSnapshotHandlerFunction.kt
- fix: mongodb missing cursor when `scanAggregateId`
=> fix: mongodb missing cursor when `scanAggregateId`

gradle.properties, wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MessageFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MethodFunctionMetadata.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MethodMessageHandler.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/DefaultDeleteAggregateFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt, wow-core/src/test/kotlin/me/ahoo/wow/event/DomainEventDispatcherTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/function/MethodFunctionMetadataTest.kt
- feat: add `NamedBoundedContext` metadata to `MessageFunction`
=> feat: add `NamedBoundedContext` metadata to `MessageFunction`

wow-api/src/main/kotlin/me/ahoo/wow/api/query/Query.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/MongoConditionConverter.kt, wow-mongo/src/test/kotlin/me/ahoo/wow/mongo/query/MongoConditionConverterTest.kt, wow-query/src/main/kotlin/me/ahoo/wow/query/ConditionConverter.kt, wow-query/src/main/kotlin/me/ahoo/wow/query/ConditionDsl.kt, wow-query/src/test/kotlin/me/ahoo/wow/query/ConditionDslTest.kt
Support `TODAY` & `TOMORROW` & `THIS_WEEK` & `NEXT_WEEK` & `LAST_WEEK` & `THIS_MONTH` & `LAST_MONTH` & `RECENT_DAYS` Operator.
=> feat(query): Support `TODAY` & `TOMORROW` & `THIS_WEEK` & `NEXT_WEEK` & `LAST_WEEK` & `THIS_MONTH` & `LAST_MONTH` & `RECENT_DAYS` Operator.

example/example-server/src/main/kotlin/me/ahoo/wow/example/server/order/OrderQueryController.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/query/QueryAutoConfiguration.kt, wow-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/query/QueryAutoConfigurationTest.kt, wow-spring/build.gradle.kts, wow-spring/src/main/kotlin/me/ahoo/wow/spring/query/SnapshotQueryServiceFactoryBean.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/query/SnapshotQueryServiceRegistrar.kt
```kotlin
@RestController
@RequestMapping("/order")
class OrderQueryController(
@Qualifier("example.order.SnapshotQueryService")
private val queryService: SnapshotQueryService<OrderState>
) {
@GetMapping("{tenantId}/{orderId}")
fun getById(@PathVariable tenantId: String, @PathVariable orderId: String): Mono<OrderState> {
return condition {
tenantId(tenantId)
id(orderId)
}.single(queryService).toState().throwNotFoundIfEmpty()
}
}
```
=> feat(query): add `SnapshotQueryServiceRegistrar` to auto register `SnapshotQueryService`

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandOperator.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/LocalFirstMessageBus.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/TraceMessagePropagator.kt
- `command.wait.*` -> `command_wait_*`
- `command.operator` -> `command_operator`
- `trace.id` -> `trace_id`
- `upstream.id` -> `upstream_id`
- `upstream.name` -> `upstream_name`
In order to better adapt to the queries of MongoDB / Elasticsearch
=> refactor: Replace dots in header names with underscores for `MessagePropagator`

test/wow-mock/src/main/kotlin/me/ahoo/wow/eventsourcing/mock/DelayEventStore.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/AbstractEventStore.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventStore.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/InMemoryEventStore.kt, wow-core/src/main/kotlin/me/ahoo/wow/metrics/MetricEventStore.kt, wow-core/src/test/kotlin/me/ahoo/wow/modeling/command/MockDelayEventStoreCommandDispatcherTest.kt, wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/eventsourcing/ElasticsearchEventStore.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/MongoEventStore.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/eventsourcing/TracingEventStore.kt, wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/EventStreamSchema.kt, wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/R2dbcEventStore.kt, wow-redis/src/main/kotlin/me/ahoo/wow/redis/eventsourcing/RedisEventStore.kt, wow-redis/src/test/kotlin/me/ahoo/wow/redis/eventsourcing/RedisEventStoreTest.kt
- Implement loadStream method for retrieving events by event time range
- Add support for event time-based loading in Elasticsearch, R2DBC, MongoDB, and Redis event stores
- Update test cases to cover new functionality
=> feat(event-store): add load event stream by event time functionality

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParser.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParserTest.kt
- Add `@Repeatable` annotation to PathVariable and HeaderVariable
- Update CommandRouteMetadataParser to handle multiple annotations
- Add test case for nested PathVariable with multiple fields
=> feat(api): support multiple PathVariable and HeaderVariable annotations

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/ComponentRef.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/schema/AggregateIdSchema.kt
- Remove unnecessary non-null assertions for schema names
- Add support for naming schemas based on named aggregates
- Use simple class name as fallback schema name
- Refactor schema name generation logic for better readability and performance
=> refactor(wow-openapi): improve schema name handling and add aggregate naming support

wow-core/src/main/kotlin/me/ahoo/wow/infra/reflection/AnnotationScanner.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParser.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParserTest.kt
- Update AnnotationScanner to use a more efficient caching mechanism
- Add support for scanning multiple annotations of the same type
- Refactor scanAnnotation to use the new scanAnnotations method
- Update CommandRouteMetadataParser to use the new scanAnnotations method
=> feat(infra): enhance annotation scanning and support multiple annotations

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/event/compensation/StateEventCompensator.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventSourcingStateAggregateRepository.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventStoreStateAggregateRepository.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/RetryableAggregateProcessor.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/state/StateAggregateFactory.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/RegenerateSnapshotHandler.kt
- Add createAsMono method to StateAggregateFactory interface
- Update implementations to use createAsMono instead of create
- Remove unnecessary toMono conversions
- Simplify code in various classes by using the new method
=> refactor(core): introduce createAsMono method in StateAggregateFactory

wow-api/src/main/kotlin/me/ahoo/wow/api/query/Condition.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/GlobalRouteSpecFactory.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/CommandResultConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/ConditionConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/DomainEventConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/ListQueryConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/PagedQueryConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/PaginationConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/ProjectionConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/SingleQueryConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/event/CountEventStreamRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/event/ListQueryEventStreamRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/event/PagedQueryEventStreamRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/CountSnapshotRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/ListQuerySnapshotRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/ListQuerySnapshotStateRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/PagedQuerySnapshotRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/PagedQuerySnapshotStateRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/SingleSnapshotRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/snapshot/SingleSnapshotStateRouteSpec.kt
- Update multiple converters to use direct assignment to the 'default' property instead of calling 'setDefault'
- This change simplifies the code and aligns with the OpenAPI library's updated approach
=> refactor(wow-openapi): replace setDefault with direct assignment to default property

wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/command/ServerCommandWaitEndpointTest.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfigurationTest.kt
- Add PrepareAutoConfigurationTest to verify the loading of PrepareProperties bean
- Add ServerCommandWaitEndpointTest to test the endpoint URL construction
=> test(wow-spring-boot-starter): add unit tests for PrepareAutoConfiguration and ServerCommandWaitEndpoint

example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/ViewCart.kt, example/example-domain/src/main/kotlin/me/ahoo/wow/example/domain/cart/Cart.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/GivenInitializationCommand.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/VoidCommand.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/command/CommandMessage.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandFactory.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/SimpleCommandMessage.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/annotation/CommandMetadataParser.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/metadata/CommandMetadata.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandDispatcher.kt, wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/serialization/command/CommandJsonSerializer.kt, wow-core/src/main/kotlin/me/ahoo/wow/serialization/command/CommandRecord.kt
- Implement VoidCommand annotation to mark commands that don't require aggregate processing
- Add isVoid property to CommandMetadata and CommandMessage
- Update CommandDispatcher to filter out void commands
- Serialize and deserialize isVoid flag in CommandRecord
=> feat(core): add support for VoidCommand

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/BoundedContextConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/CommandResultConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/MessageHeaderConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/WaitSignalConverter.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/WowMetadataConverter.kt, wow-openapi/src/main/resources/META-INF/services/io.swagger.v3.core.converter.ModelConverter
- Add BoundedContextConverter to allow additional properties for aggregates
- Update CommandResultConverter to use CommandResultCapable and allow additional properties
- Modify ConditionConverter to set additional properties for options
- Add new converters for WaitSignal, WowMetadata, and MessageHeader
- Update BoundedContextSchemaNameConverter to resolve schema names for non-standard library classes
=> feat(openapi): add converters for various types to handle additional properties

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/mock/MockAggregate.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandDispatcher.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/LocalFirstCommandBusTest.kt
- Add support for void commands in LocalFirstCommandBus
- Implement optimized receive method in CommandDispatcher
- Add test case for void command handling
- Update MockAggregate to include void command example
=> feat(command): support void command and optimize command dispatching

wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/LocalFirstCommandBus.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/CommandDispatcher.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/DefaultCommandGatewayTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/LocalFirstCommandBusTest.kt
- Add check to prevent using PROCESSED stage with void commands
- Update test cases to cover the new validation
- Improve test readability by renaming and reorganizing test methods
=> fix(command): add validation for void command wait strategy

wow-core/src/test/kotlin/me/ahoo/wow/command/LocalFirstCommandBusTest.kt
- Replace verifyTimeout with more specific message content verification
- Check if the received message ID and isVoid flag match the expected values
- Update test to cancel subscription after receiving the expected message
=> test(wow-core): update LocalFirstCommandBusTest to verify message content

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/AggregateRequest.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandFacadeHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandler.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandMessageParser.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/event/EventCompensateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/event/LoadEventStreamHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/CountQueryHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/ListQueryHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/PagedQueryHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/ListQuerySnapshotStateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/LoadSnapshotHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/PagedQuerySnapshotStateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/RegenerateSnapshotHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotStateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/AbstractLoadAggregateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/AggregateTracingHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/IdsQueryAggregateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/LoadTimeBasedAggregateHandlerFunction.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/handler/CommandHandlerTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandFacadeHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/DefaultCommandMessageParserTest.kt
- Introduce new CommandMessageParser interface and DefaultCommandMessageParser implementation
- Remove static methods from CommandParser object
- Update related classes to use the new CommandMessageParser
- Rename CommandParserTest to DefaultCommandMessageParserTest
=> refactor(webflux): introduce CommandMessageParser and remove CommandParser

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandMessageParser.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandRequestHeaderAppender.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/DefaultCommandMessageParserTest.kt
- Introduce CommandRequestHeaderAppender interface for flexible header handling
- Implement CommandRequestExtendHeaderAppender for extended headers
- Update DefaultCommandMessageParser to use CommandRequestHeaderAppender
- Add commandRequestExtendHeaderAppender bean in WebFluxAutoConfiguration
- Modify commandMessageParser bean to accept CommandRequestHeaderAppender
=> feat(webflux): enhance command message parsing with customizable header appender

wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/CommandRequestHeaderPropagator.kt, wow-core/src/main/resources/META-INF/services/me.ahoo.wow.messaging.propagation.MessagePropagator, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/CommandRequestHeaderPropagatorTest.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandMessageParser.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandRequestHeaderAppender.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandRequestUserAgentHeaderAppenderTest.kt
- Implement CommandRequestUserAgentHeaderAppender to add user agent and remote IP to command header
- Update CommandMessageParser to use the new appender
- Add CommandRequestHeaderPropagator to handle user agent and remote IP propagation
- Include new propagator in META-INF/services
- Add unit tests for new functionality
=> feat(webflux): add user agent and remote IP to command header

build.gradle.kts, compensation/wow-compensation-server/build.gradle.kts, example/example-server/build.gradle.kts, example/transfer/example-transfer-server/build.gradle.kts, gradle/libs.versions.toml, wow-compiler/build.gradle.kts, wow-dependencies/build.gradle.kts, wow-spring-boot-starter/build.gradle.kts
- Update Gradle plugins and dependencies across multiple project modules
- Refactor import statements to use updated dependency versions
- Replace deprecated plugins with their latest equivalents
- Update version references in libs.versions.toml to follow new naming conventions
=> build: update Gradle project configurations and dependencies

build.gradle.kts, gradle/libs.versions.toml
- Update `publish-plugin` to `publish` in build.gradle.kts
- Update `publish-plugin` to `publish` in gradle/libs.versions.toml
=> build: update Gradle plugins and dependencies

gradle/libs.versions.toml, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForAfterProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForEventHandled.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForProjected.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForSagaHandled.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForSnapshot.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SimpleWaitStrategyRegistrarTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- Remove the static methods in the WaitingFor class and implement them in the companion object instead
- Add multiple waiting strategy implementation classes to handle different command stages
- Optimize the registration and handling logic of waiting strategies
- Update relevant test cases
=> refactor(wow-core): WaitStrategy

wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/ListQueryHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/query/SingleQueryHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/ListQuerySnapshotStateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/PagedQuerySnapshotStateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/SingleSnapshotStateHandlerFunction.kt
- Abstract ListQueryHandlerFunction, PagedQueryHandlerFunction, and SingleQueryHandlerFunction
- Create generic QueryHandlerFunctionFactory for different query types
- Refactor SnapshotStateHandlerFunction to use QueryHandlerFunctionFactory
- Add support for rewriting query results in factories
=> refactor(wow-webflux): generalize query handler functions

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/AggregateRoute.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/snapshot/LoadSnapshotHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/AbstractLoadAggregateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/LoadTimeBasedAggregateHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/state/OwnerAggregatePrecondition.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/snapshot/LoadSnapshotHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadAggregateHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadTimeBasedAggregateHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/OwnerAggregatePreconditionTest.kt
- Implement OwnerAggregatePrecondition to check owner access for aggregates
- Add owner check in LoadSnapshotHandlerFunction and LoadTimeBasedAggregateHandlerFunction
- Update AggregateRoute.Owner to use boolean value for owned status
- Add tests for OwnerAggregatePrecondition
=> feat(route): add owner aggregate precondition check

documentation/docs/guide/query.md
- Added OWNER_ID operator to the query documentation table
- This operator matches documents where the `ownerId` field value is equal to the specified value
=> docs(guide): add OWNER_ID operator to query documentation

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/ReactiveSnapshotQueryApi.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParser.kt
- Rename DEFAULT_COMMAND_PATH to DEFAULT_COMMAND_ACTION for better clarity
- Add JavaDoc for the 'path' property
- Deprecate 'ignoreAggregateNamePrefix' property
=> refactor(api): update CommandRoute annotation and deprecate a property

example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/ChangeAddress.kt, example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/CreateOrder.kt, example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/ReceiptOrder.kt, example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/ShipOrder.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/command/DeleteAggregate.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/command/RecoverAggregate.kt, wow-models/src/main/kotlin/me/ahoo/wow/models/tree/command/Create.kt, wow-models/src/main/kotlin/me/ahoo/wow/models/tree/command/Delete.kt, wow-models/src/main/kotlin/me/ahoo/wow/models/tree/command/Move.kt, wow-models/src/main/kotlin/me/ahoo/wow/models/tree/command/Update.kt, wow-models/src/test/kotlin/me/ahoo/wow/models/tree/command/CreateCategory.kt, wow-models/src/test/kotlin/me/ahoo/wow/models/tree/command/DeleteCategory.kt, wow-models/src/test/kotlin/me/ahoo/wow/models/tree/command/MoveCategory.kt, wow-models/src/test/kotlin/me/ahoo/wow/models/tree/command/UpdateCategory.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadata.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParser.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParserTest.kt
- Rename CommandRoute.path to CommandRoute.action
- Update related metadata and parser to use new action property
- Adjust path generation logic to use action instead of path
- Update example and test cases to reflect the new changes
=> refactor(api): remove CommandRoute.ignoreAggregateNamePrefix

wow-core/src/main/kotlin/me/ahoo/wow/naming/NamingConverter.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/AggregateSchemaInitializer.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/EventStreamSchemaInitializer.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/SnapshotSchemaInitializer.kt
- Add createOwnerIdIndex function to AggregateSchemaInitializer
- Implement createOwnerIdIndex in EventStreamSchemaInitializer and SnapshotSchemaInitializer
- Remove toAggregateIdCollectionName function and related collections
- Update NamingConverter to use functional interface
=> feat(mongodb): add owner ID index and remove aggregate ID collection

example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/PayOrder.kt, example/example-api/src/main/kotlin/me/ahoo/wow/example/api/order/ShipOrder.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadata.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParser.kt
- Add appendOwnerPath parameter to CommandRoute annotation
- Update CommandRouteMetadata and CommandRouteMetadataParser to support appendOwnerPath
- Modify CommandRouteSpec to handle appendOwnerPath option
- Update example commands to use appendOwnerPath instead of appendIdPath
=> feat(api): add appendOwnerPath option for command route

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OwnerId.kt, wow-core/src/main/kotlin/me/ahoo/wow/annotation/AnnotationPropertyAccessorParser.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandFactory.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/annotation/CommandMetadataParser.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/metadata/CommandMetadata.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/CommandFactoryTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/MockCommands.kt
- Add OwnerId annotation and related property getter
- Update CommandFactory to handle owner id
- Extend CommandMetadata with ownerIdGetter
- Update CommandMetadataParser to parse owner id
- Add unit tests for owner id functionality
=> feat(core): add owner id support for commands

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandFacadeRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/command/CommandRouteSpec.kt
- Remove COMMAND_OWNER_PARAMETER from CommandFacadeRouteSpec
- Add OWNER_ID_PARAMETER ref to CommandFacadeRouteSpec- Update CommandRouteSpec to include OWNER_ID_PARAMETER
- Refactor code to use ParameterRef for better reusability
=> refactor(wow-openapi): replace COMMAND_OWNER_PARAMETER with OWNER_ID_PARAMETER ref

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/EmptyClassConverter.kt, wow-openapi/src/main/resources/META-INF/services/io.swagger.v3.core.converter.ModelConverter
- Implement EmptyClassConverter to handle empty classes in Swagger
- Register EmptyClassConverter in META-INF/services/io.swagger.v3.core.converter.ModelConverter
=> feat(wow-openapi): add empty class converter for Swagger

wow-cocache/src/main/kotlin/me/ahoo/wow/cache/CacheValueTtlConfiguration.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/RefreshMode.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/StateCacheRefresher.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/StateCacheRefresherTest.kt
- Add CacheValueTtlConfiguration interface for cache TTL configuration
- Update LoadCacheSourceConfiguration to implement CacheValueTtlConfiguration
- Introduce RefreshMode enum for different cache refreshing strategies
- Implement StateCacheRefresher class for proactive cache refreshing
- Add unit tests for StateCacheRefresher functionality
=> feat(cache): implement StateCacheRefresher for proactive cache refreshing

wow-cocache/src/main/kotlin/me/ahoo/wow/cache/StateToCacheDataConverter.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/StateToCacheDataConverterTest.kt
- Update the identity() method in StateToCacheDataConverter to use a single type parameter
- Adjust the corresponding test case to use the new method signature
- This change improves type safety and reduces unnecessary type casting
=> refactor(cache): optimize StateToCacheDataConverter.identity() method

wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/EvictStateCacheRefresher.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/SetStateCacheRefresher.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/StateCacheRefresher.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/source/LoadCacheSourceConfiguration.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/source/QueryApiCacheSource.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/source/QueryServiceCacheSource.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/source/StateCacheSource.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/refresh/EvictStateCacheRefresherTest.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/refresh/SetStateCacheRefresherTest.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/source/QueryApiCacheSourceTest.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/source/QueryServiceCacheSourceTest.kt
- Rename StateCacheRefresher to EvictStateCacheRefresher
- Create new SetStateCacheRefresher class
- Update related test files
- Refactor StateCacheRefresher into an abstract class
- Rename other cache-related classes for better organization
=> refactor(cache): split StateCacheRefresher into separate classes

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/AfterCommand.kt
- Add KotlinDoc comment for the AfterCommand annotation
- Explain the purpose and usage of the annotation
- Mention the behavior when the return value is not null
=> docs(wow-api): add AfterCommand annotation documentation

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/AfterCommand.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/AfterCommandFunction.kt, wow-core/src/test/kotlin/me/ahoo/wow/modeling/annotation/MockAggregates.kt, wow-core/src/test/kotlin/me/ahoo/wow/modeling/command/AfterCommandFunctionTest.kt
- Update AfterCommand annotation to use include/exclude instead of commands
- Modify AfterCommandFunction to handle new include/exclude logic
- Add tests for new AfterCommand matching behavior
- Update MockAggregates to demonstrate new AfterCommand usage
=> feat(api): enhance AfterCommand with include/exclude functionality

wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/EvictStateCacheRefresher.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/SetStateCacheRefresher.kt, wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/StateCacheRefresher.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/refresh/EvictStateCacheRefresherTest.kt, wow-cocache/src/test/kotlin/me/ahoo/wow/cache/refresh/SetStateCacheRefresherTest.kt
- Abstract StateCacheRefresher now supports generic DomainEventExchange
- Update EvictStateCacheRefresher and SetStateCacheRefresher to use new generic type
- Modify related test cases to accommodate the new generic structure
- Add functionKind property to StateCacheRefresher implementations
=> refactor(cache-refresh): generalize StateCacheRefresher and update related tests

wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/ReactiveSnapshotQueryApi.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/SnapshotCountQueryApi.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/SnapshotListQueryApi.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/SnapshotPagedQueryApi.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/SnapshotSingleQueryApi.kt, wow-apiclient/src/main/kotlin/me/ahoo/wow/apiclient/query/SyncSnapshotQueryApi.kt
- Divide ReactiveSnapshotQueryApi into SnapshotSingleQueryApi, SnapshotListQueryApi, SnapshotPagedQueryApi, and SnapshotCountQueryApi
- Update SyncSnapshotQueryApi to implement new interfaces
- Remove redundant method declarations and annotations
- Improve code organization and readability
=> refactor(query): split ReactiveSnapshotQueryApi into separate interfaces

build.gradle.kts
- Add javaParameters = true for Kotlin compiler
- Move -parameters argument from JavaCompile to KotlinCompile
- This change improves reflection capabilities in Kotlin
=> build(gradle): adjust compiler arguments for improved reflection

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategyRegistrar.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForAfterProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingForProcessed.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SimpleWaitStrategyRegistrarTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- Update CommandGateway to use new WaitStrategy interface
- Refactor DefaultCommandGateway to implement new sendAndWait method
- Modify SimpleWaitStrategyRegistrar to handle command completion
- Update WaitingFor and related classes to use Flux instead of Mono
- Improve test coverage for new WaitStrategy behavior
=> refactor(command): redesign WaitStrategy and related components

wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/Responses.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/AggregateRequest.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandler.kt
- Rename the `isEventStream` function to `isSse` for better readability and consistency
- Update function calls in `CommandHandler` and `Responses` to use the new `isSse` name
=> refactor(webflux): rename `isEventStream` to `isSse`

wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt
- Remove duplicate unregister logic in DefaultCommandGateway
- Add onFinally method to WaitingFor interface
- Implement onFinally in WaitStrategy
- Update wait strategy registration and unregistration process
=> refactor(command): improve wait strategy and unregister command

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitSignal.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/CommandResultTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/LocalCommandWaitNotifierTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SimpleWaitStrategyRegistrarTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/Responses.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/ResponsesKtTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/wait/CommandWaitHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/wait/WebClientCommandWaitNotifierTest.kt
- Add global ID generation to CommandResult and WaitSignal
- Update related tests to include new ID field
- Adjust CommandGateway and wait notifier implementations
=> refactor(command): add global ID to CommandResult and WaitSignal

wow-cocache/src/main/kotlin/me/ahoo/wow/cache/refresh/StateCacheRefresher.kt
- Add `Schedulers.boundedElastic()` to `StateCacheRefresher.invoke()` method
- This change allows cache refresh operations to be executed on a separate thread, improving overall performance
=> refactor(caching): improve cache refresher performance

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- Rename doFinally to onFinally for better clarity
- Allow multiple onFinally hooks to be registered
- Implement safeDoFinally to handle exceptions in onFinally hooks
- Update DefaultCommandGateway to use new onFinally method
- Modify CommandGatewaySpec to demonstrate usage of onFinally
=> fix(wow-core): improve WaitStrategy to handle multiple onFinally hooks

.idea/modules.xml, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/DefaultCommandGatewayTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- Remove CountDownLatch imports and usage from CommandGatewaySpec
- Update wait strategy tests to not rely on CountDownLatch
- Add check for double onFinally assignment in WaitingFor
=> test(wow-tck): remove CountDownLatch usage in CommandGatewaySpec

wow-schema/src/main/kotlin/me/ahoo/wow/schema/JsonSchemaGenerator.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaDefinitionNamingStrategy.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPICompatibilityAttributeOverride.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaDefinitionNamingStrategyTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Add OpenAPICompatibilityAttributeOverride to replace exclusive min/max attributes
- Implement OpenAPISchemaBuilder for generating OpenAPI-compatible schemas
- Update WowModule to include empty instance attribute override
- Modify WowSchemaDefinitionNamingStrategy to fall back to default strategy
- Add tests for new OpenAPI schema builder and naming strategy
=> feat(schema): add OpenAPI compatibility and improve schema generation

wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Introduce DefaultCustomizer and InlineCustomizer classes to handle schema customization
- Update to use SchemaVersion.DRAFT_2020_12 by default
- Refactor customizer logic to improve code organization and readability
- Update test cases to use new customizer approach
=> refactor(wow-schema): update OpenAPISchemaBuilder with new customizer approach

wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinCustomDefinitionProvider.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- Update KotlinCustomDefinitionProvider to exclude enum types
- Enable simplified enums option in OpenAPISchemaBuilder
- Add test case for enum type generation
- Refactor test cases to use asJsonSchema() method
=> feat(schema): add enum support and simplify enum definitions

wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategy.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
- Rename WowSchemaDefinitionNamingStrategy to WowSchemaNamingStrategy
- Update WowModule to use the new naming strategy
- Rename related test files and update test content to match the new strategy
=> refactor(schema): rename schema naming strategy and update related tests

wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AbstractStateAggregate.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregateIdDefinitionProvider.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/DomainEventStreamDefinitionProvider.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/MessageDefinitionProvider.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/TypedCustomDefinitionProvider.kt
- Move AbstractStateAggregate, AggregateIdDefinitionProvider, DomainEventStreamDefinitionProvider, MessageDefinitionProvider, and TypedCustomDefinitionProvider to new typed package
- Update package name from me.ahoo.wow.schema to me.ahoo.wow.schema.typed
- Add imports for new typed classes in WowModule.kt
=> refactor(schema): create typed package for typed classes

wow-schema/build.gradle.kts, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/joda/money/CurrencyUnitDefinitionProvider.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/joda/money/MoneyDefinitionProvider.kt, wow-schema/src/main/resources/META-INF/wow-schema/CurrencyUnit.json, wow-schema/src/main/resources/META-INF/wow-schema/Money.json, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- Add CurrencyUnitDefinitionProvider and MoneyDefinitionProvider for Joda Money
- Update WowModule to include Joda Money support
- Add JODA_MONEY option to WowOption
- Create JSON schemas for CurrencyUnit and Money
- Update JsonSchemaGeneratorTest to include Joda Money classes
- Add jackson-datatype-joda-money as an implementation dependency
=> feat(schema): add Joda Money support

wow-core/src/test/kotlin/me/ahoo/wow/event/annotation/EventProcessorParserTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/function/FunctionMetadataParserTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/projection/annotation/ProjectionProcessorMetadataParserTest.kt
- Change contextName from 'wow-core-test' to 'wow.event' in EventProcessorParserTest
- Update contextName from 'wow-core-test' to 'wow.messaging' in FunctionMetadataParserTest
- Modify contextName from 'wow-core-test' to 'wow' in ProjectionProcessorMetadataParserTest
=> test: update context name to wow.event or wow.messaging in metadata tests

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouteSpecFactory.kt
- Changed the initialize method in RouteSpecFactory interface to not explicitly return Unit
- This change simplifies the method signature and improves code readability
=> refactor(wow-openapi): remove redundant Unit return type in RouteSpecFactory.initialize

wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverterTest.kt
- Add test cases to verify schema name conversion for different types of classes
- Test coverage includes aggregate, Java library, and custom Java class
- Ensure proper schema name resolution for bounded context
=> test.openapi: add unit tests for BoundedContextSchemaNameConverter

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandFacadeRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- Extracted commandResponses() function in CommandComponent to centralize response creation
- Updated CommandFacadeRouteSpec and CommandRouteSpec to use the new centralized function
- Removed duplicate response creation code from individual route specs
=> refactor(wow-openapi): extract command responses into a single function

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandFacadeRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- Extract commandCommonHeaderParameters() function in CommandComponent
- Update CommandFacadeRouteSpec and CommandRouteSpec to use the new function
- Remove duplicate header parameter imports and additions in route specs
=> refactor(wow-openapi): extract common header parameters for command

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/event/CountEventStreamRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/state/LoadAggregateComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/state/LoadAggregateRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/state/LoadTimeBasedAggregateRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/state/LoadVersionedAggregateRouteSpec.kt
- Create LoadAggregateComponent object to centralize response handling
- Update CountEventStreamRouteSpec to use Https.Code.OK for consistency
- Refactor LoadAggregateRouteSpec, LoadTimeBasedAggregateRouteSpec, and LoadVersionedAggregateRouteSpec to use the new LoadAggregateComponent
- Remove redundant response building code from individual route specs
=> refactor(wow-openapi): extract load aggregate responses to common component

wow-openapi/src/main/resources/META-INF/wow-metadata.json, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverterTest.kt
- Add test case for BatchResult schema resolution in BoundedContextSchemaNameConverterTest
- Create wow-metadata.json with context configuration for wow.openapi
=> test(wow-openapi): add BatchResult schema resolution and update metadata

wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinNullableCheck.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinReadOnlyCheck.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinRequiredCheck.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinWriteOnlyCheck.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt
- Add support for @Schema annotation in Kotlin classes
- Implement nullable, readOnly, required, and writeOnly checks using @Schema
- Update JsonSchemaGenerator to handle new schema annotations
- Modify existing checks to respect @Schema when present
=> feat(schema): support OpenAPI schema annotations for Kotlin

.idea/modules/Wow.test.iml, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregatedDomainEventStreamDefinitionProvider.kt, wow-schema/src/main/resources/META-INF/wow-schema/AggregatedDomainEventStream.json, wow-schema/src/main/resources/META-INF/wow-schema/DomainEventStreamBody.json, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/resources/META-INF/wow-schema/CartAggregatedDomainEventStream.json
- Add AggregatedDomainEventStream JSON schema definition
- Update AggregatedDomainEventStreamDefinitionProvider to use new schema
- Generate CartAggregatedDomainEventStream JSON schema as an example
- Add DomainEventStreamBody JSON schema as a reusable component
- Update JsonSchemaGeneratorTest to use new schema for Cart aggregate
=> feat(schema): generate AggregatedDomainEventStream JSON schema

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/Https.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/AggregateRequest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandFacadeHandlerFunctionTest.kt
- Change SSE acceptance check to use firstOrNull instead of contains
- Add accept header parameter to OpenAPI documentation
- Update CommandFacadeHandlerFunctionTest to use MockServerRequest
- Refactor CommandFacadeHandlerFunction creation for better reusability
=> refactor(webflux): improve SSE acceptance check and add accept header parameter

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandComponent.kt
- Update the response schema to handle both successful and error cases
- Add a 'StringSchema' for error messages in the text event stream
- Refactor the commandResultSchema to be reusable in different content types
=> refactor(wow-openapi): improve command response schema for text event stream

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt
- Update summary property to use command name if summary is blank
- Improve documentation clarity for command route summaries
=> feat(CommandRouteSpec): enhance summary with fallback to command name

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/global/CommandWaitRouteSpec.kt
- Change summary from "command wait handler" to "The receiving endpoint of the wait signal"
- Improve clarity and consistency in API documentation
=> docs(wow-openapi): update summary for CommandWaitRouteSpec

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt
- Remove unused constants PAGED_LIST_EVENT_STREAM_RESPONSE_KEY and LOAD_EVENT_STREAM_RESPONSE_KEY
- Refactor pagedListEventStreamResponse and loadEventStreamResponse methods to use ApiResponseBuilder
=> refactor(wow-openapi): remove unused constants and refactor response building

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadata.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadataParser.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParserTest.kt
- Add 'field' property to VariableMetadata to store Java Field reference
- Update CommandRouteMetadataParser to populate 'field' in VariableMetadata
- Add test case to verify 'field' property in VariableMetadata
=> feat(metadata): add field information to VariableMetadata

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/metadata/BoundedContextResolver.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/metadata/CommandAggregateRootResolver.kt, wow-compiler/src/test/kotlin/me/ahoo/wow/compiler/Compiles.kt, wow-compiler/src/test/kotlin/me/ahoo/wow/compiler/metadata/MetadataSymbolProcessorTest.kt, wow-compiler/src/test/kotlin/me/ahoo/wow/compiler/query/QuerySymbolProcessorTest.kt, wow-core/src/main/kotlin/me/ahoo/wow/configuration/WowMetadata.kt, wow-core/src/test/kotlin/me/ahoo/wow/configuration/AggregateTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/configuration/NamedBoundedContextTest.kt
- Refactor compileTest function to accept a consumer callback
- Add metadata validation for MetadataSymbolProcessor
- Update tests for QuerySymbolProcessor to use new compileTest structure
=> test(wow-compiler): refactor compileTest and add metadata validation

wow-core/src/main/kotlin/me/ahoo/wow/infra/reflection/AnnotationScanner.kt, wow-core/src/main/kotlin/me/ahoo/wow/infra/reflection/IntimateAnnotationElement.kt, wow-core/src/test/java/me/ahoo/wow/infra/reflection/JvmRepeatableTag.java, wow-core/src/test/java/me/ahoo/wow/infra/reflection/JvmRepeatableTags.java, wow-core/src/test/java/me/ahoo/wow/infra/reflection/MockRepeatableClass.java, wow-core/src/test/kotlin/me/ahoo/wow/infra/reflection/AnnotationScannerTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/infra/reflection/IntimateAnnotationElementTest.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/route/CommandRouteMetadataParserTest.kt
- Introduce IntimateAnnotationElement class to encapsulate annotation scanning logic
- Refactor AnnotationScanner to use the new IntimateAnnotationElement
- Add support for repeatable annotations in Java
- Improve performance by caching IntimateAnnotationElement instances
- Remove redundant tests and simplify existing ones
=> refactor(infra-reflection): redesign annotation scanning mechanism

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouteSpec.kt
- Change countQueryResponse media type from TEXT_PLAIN to APPLICATION_JSON
- Add TEXT_PLAIN to accepted media types in RouteSpec
=> refactor(wow-openapi): adjust media types for query responses and route acceptance

wow-core/src/main/kotlin/me/ahoo/wow/command/factory/CommandBuilderRewriter.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/factory/BlockingCommandBuilderRewriterTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/factory/SimpleCommandBuilderRewriterRegistryTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/reactor/SchedulerTest.kt
- Introduce BlockingCommandBuilderRewriter to handle blocking operations
- Update CommandBuilderRewriter interface to include blocked property
- Modify CommandBuilderRewriterRegistry to support registration of blocking rewriters
- Add test case for registering blocked command builder rewriter
=> feat(command): add support for blocking command builder rewriter

wow-schema/src/main/kotlin/me/ahoo/wow/schema/JsonSchemaGenerator.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinIgnoreCheck.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/kotlin/KotlinModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaValidatorTest.kt
- Add KotlinModule to handle Kotlin-specific schema generation
- Introduce KotlinIgnoreCheck to filter out synthetic fields
- Update JsonSchemaGenerator and OpenAPISchemaBuilder to include KotlinModule
- Remove redundant Kotlin-related code from WowModule
- Adjust unit tests to reflect new Kotlin integration
=> feat(schema): integrate Kotlin support into JSON schema generation

wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/TenantId.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandFactory.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/CommandFactoryTest.kt
- Replace direct default ID usage with new extension functions
- Add orDefaultTenantId() function to TenantId companion object
- Use orDefaultOwnerId() function from OwnerId companion object
- Improve code readability and reduce repetition
=> refactor(command): use extension functions for default ID handling

build.gradle.kts, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/AccountKTest.kt, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/TransferSagaKTest.kt, gradle/libs.versions.toml, test/wow-test/build.gradle.kts, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt, wow-dependencies/build.gradle.kts
- Remove Hamcrest dependency from various test configurations
- Add AssertJ dependency to testImplementation configuration
- Update test code to use AssertJ assertions instead of Hamcrest
- Refactor test expectations to use AssertJ's fluent API
- Remove redundant Hamcrest imports and replace with AssertJ
=> test: replace Hamcrest with AssertJ for unit testing

wow-core/src/test/kotlin/me/ahoo/wow/serialization/event/StateJsonRecordTest.kt
- Replace toState<MockState>() with state<MockState>() in StateJsonRecordTest
- This change improves code readability and follows the recent refactoring
=> test(wow-core): update StateJsonRecordTest to use state() method

example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/AccountKTest.kt, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/TransferSagaKTest.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/event/DomainEventStreamSpec.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/assert/Jdk.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/assert/JdkConcurrent.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/assert/JdkFunction.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/assert/JdkIO.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/assert/JdkTime.kt, wow-core/src/test/kotlin/me/ahoo/wow/annotation/AnnotationPropertyAccessorParserTest.kt
- Add assert extension functions for Boolean, Byte, Short, Int, Long, Float, Double, BigDecimal, String, Collection, List, Map, Optional, Future, Predicate, File, Path, URL, URI, Date, ZonedDateTime, Temporal, LocalDateTime, OffsetDateTime, OffsetTime, LocalTime, LocalDate, YearMonth, Instant, Duration, and Period types
- Update existing test files to use new assert extension functions
- Remove redundant imports of Assertions class in test files
=> test: add assert extension functions for common JDK types

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/EventStoreSpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/eventsourcing/StateAggregateRepositorySpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/messaging/MessageBusSpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/command/CommandDispatcherSpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/modeling/state/StateAggregateFactorySpec.kt, test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/prepare/PrepareKeySpec.kt
- Remove import statements for Hamcrest
- Add import statement for me.ahoo.test.asserts.assert
- Replace assertThat() with assert().isEqualTo() for equality checks
- Replace equalTo() with isTrue() for boolean checks
- Use isNotNull() instead of notNullValue()
- Remove unnecessary MatcherAssert and Matchers imports
=> test: replace Hamcrest with me.ahoo.test.asserts in test cases

README.md, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrchestrationTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrderSagaTest.kt
- Refactor CartTest to use assert() instead of assertThat()
- Update Order related tests to use generateGlobalId() instead of GlobalIdGenerator
- Remove unnecessary imports and simplify test code
=> test: update CartTest and Order related tests

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/command/CommandRouteSpec.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/BatchResultTest.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/RouterSpecsTest.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/TagsTest.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverterTest.kt
- Replaced `field?.type` with `variableType` for clarity and consistency.
=> refactor(CommandRouteSpec): Update variableType usage

wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategy.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/TypesTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
Add a new test class `TypesTest` to verify the behavior of `isWowType` and `isStdType` methods. The tests cover various types to ensure that the methods correctly identify WoW-specific and standard types.
- Added tests for `AggregateId`, `CommandMessage`, `DomainEvent`, `DomainEventStream`, `Snapshot`, `StateAggregate`, and `StateEvent` to check `isWowType`.
- Added tests for `String`, `Int`, and `List` to check both `isWowType` and `isStdType`.
Also, removed an unused import and a redundant condition in `WowSchemaNamingStrategy`.
=> test(wow-schema): Add TypesTest for isWowType and isStdType methods

wow-schema/src/main/kotlin/me/ahoo/wow/schema/IgnoreCommandRouteVariableCheck.kt
- Combine conditions for checking `CommandRoute.PathVariable` and `CommandRoute.HeaderVariable`.
- Remove redundant return statements.
- Ensure `nestedPath` is empty before returning true.
=> refactor(wow-schema): Simplify and optimize IgnoreCommandRouteVariableCheck

wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/CommandRoute.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/metadata/CommandRouteMetadataParserTest.kt
Add a new test case to verify the behavior when a path variable is missed in the `CommandRoute` annotation. This ensures that the `pathVariableMetadata` correctly identifies and handles missing fields.
=> test(wow-openapi): Add test for missed variable in CommandRouteMetadataParser

example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrderTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/annotation/SortedByOrderKtTest.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/stereotype/EventProcessor.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/stereotype/ProjectionProcessor.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/stereotype/StatelessSaga.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/DefaultExceptionHandlerTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/ErrorHttpStatusMappingTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/bi/GenerateBIScriptHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/wait/CommandWaitHandlerFunctionTest.kt
- Switched from using `assertThat` to `assert` for test assertions, improving readability and consistency.
- Updated the `@Deprecated` annotations in `StatelessSaga`, `ProjectionProcessor`, and `EventProcessor` to include detailed messages and import statements, making deprecation warnings more informative.
=> Update Test Assertions and Deprecation Warnings

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt
- Added `skip` method to `Stages` in both `aggregate` and `saga/stateless` packages.
- Improved assertion messages for better clarity and readability.
=> Add skip method and improve assertions in Stages

documentation/docs/guide/getting-started.md
- Update the download link for the project template to point to the latest version (v5.11.0).
=> Update project template download link in guide

compensation/wow-compensation-api/src/test/kotlin/me/ahoo/wow/compensation/api/query/RetrySpecTest.kt, compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/CommandSortTest.kt, compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/DefaultNextRetryAtCalculatorTest.kt, compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedStateTest.kt, compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedTest.kt, compensation/wow-compensation-server/src/test/kotlin/me/ahoo/wow/compensation/server/failed/SnapshotFindNextRetryTest.kt, compensation/wow-compensation-server/src/test/kotlin/me/ahoo/wow/compensation/server/webhook/TemplateEngineTest.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/annotation/OnStateEvent.kt, wow-api/src/test/kotlin/me/ahoo/wow/api/command/DefaultDeleteAggregateTest.kt, wow-api/src/test/kotlin/me/ahoo/wow/api/messaging/function/FunctionInfoDataKtTest.kt, wow-api/src/test/kotlin/me/ahoo/wow/api/query/MaterializedSnapshotTest.kt, wow-api/src/test/kotlin/me/ahoo/wow/api/query/PagedListTest.kt, wow-bi/src/test/kotlin/me/ahoo/wow/bi/ScriptEngineTest.kt, wow-bi/src/test/kotlin/me/ahoo/wow/bi/expansion/StateExpansionScriptGeneratorTest.kt
- Replaced `org.hamcrest.MatcherAssert` and `org.junit.jupiter.api.Assertions` with `me.ahoo.test.asserts.assert`
- Updated the `ExecutionFailedStateTest`, `DefaultNextRetryAtCalculatorTest`, `ExecutionFailedTest`, and `CommandSortTest` to use the new assertion methods
- Simplified some test cases by removing redundant assertions
- This change aims to standardize the way assertions are handled in the tests, making them more consistent and readable.
=> refactor(tests): update assertions to use custom assert methods

wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaValidatorTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/TypesTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaLoaderTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
Replaced the use of Hamcrest and JUnit assertions with custom assert functions from `me.ahoo.test.asserts` for consistency and improved readability. This change affects multiple test files including `JsonSchemaTest`, `WowSchemaLoaderTest`, `JsonSchemaGeneratorTest`, `JsonSchemaValidatorTest`, `TypesTest`, and `OpenAPISchemaBuilderTest`.
- Updated imports to include `assert` and `assertThrownBy` where necessary.
- Replaced `assertThat` and `Assertions.assert*` calls with equivalent `assert` and `assertThrownBy` methods.
=> refactor(test): replace assertion libraries with custom assert functions

wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategy.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Enhanced `namePrefix` null check and append logic in `WowSchemaNamingStrategy`.
- Added a test case to verify the presence of "StringObjectMap" in `OpenAPISchemaBuilderTest`.
- Included additional test cases for map types in `WowSchemaNamingStrategyTest`.
=> feat(wow-schema): Support `Map` class in `WowSchemaNamingStrategy`

wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategy.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/WowSchemaNamingStrategyTest.kt
- Removed unused import and `baseStrategy` field.
- Updated `toSchemaName` method to always return a string.
- Adjusted test cases to reflect the changes in `toSchemaName`.
=> feat(wow-schema): Simplify SchemaNamingStrategy and update tests

compensation/wow-compensation-server/src/main/kotlin/me/ahoo/wow/compensation/server/scheduler/SchedulerProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/BusProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/WowProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/command/CommandProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/compensation/CompensationProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/elasticsearch/ElasticsearchProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/eventsourcing/snapshot/SnapshotProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/kafka/KafkaProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/mongo/MongoProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/openapi/OpenAPIProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/r2dbc/R2dbcProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/redis/RedisProperties.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxProperties.kt
- Remove EnabledCapable interface from wow-spring-boot-starter
- Use EnabledCapable interface from wow-api-naming instead
- Update import statements in multiple files to use the new interface
=> refactor(wow-spring-boot-starter): remove duplicate EnabledCapable interface

wow-core/src/main/kotlin/me/ahoo/wow/modeling/DefaultAggregateId.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/MaterializedNamedAggregate.kt
- Add transient hashCode property to DefaultAggregateId
- Add transient hashCode property to MaterializedNamedAggregate
- These changes can enhance performance by avoiding repeated hash calculations
=> perf: add transient hash codes to improve performance

wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/saga/StatelessSagaAutoConfigurationTest.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/AutoRegistrar.kt
- Simplify the stop logic in AutoRegistrar by removing unnecessary if statement
- Add test coverage for AutoRegistrar start and stop operations in StatelessSagaAutoConfigurationTest
=> refactor(wow-spring): optimize AutoRegistrar stop logic and add test coverage

wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Add `definitionPath` parameter to OpenAPISchemaBuilder constructor
- Use `definitionPath` instead of fixed constant in build method
- Update test to use custom definition path and verify its usage
=> feat(schema): make definition path configurable in OpenAPISchemaBuilder

wow-core/src/main/kotlin/me/ahoo/wow/serialization/JsonSerializer.kt, wow-core/src/test/kotlin/me/ahoo/wow/serialization/JsonSerializerTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/serialization/event/StateJsonRecordTest.kt, wow-r2dbc/src/main/kotlin/me/ahoo/wow/r2dbc/R2dbcEventStore.kt
- Add toObjectNode extension function to String class for easier conversion to ObjectNode
- Update usage in tests and R2dbcEventStore to use the new function
- Remove redundant type casting when converting JSON string to ObjectNode
=> feat(serialization): add toObjectNode extension function for String

.github/workflows/codecov.yml, .github/workflows/compensation-test.yml, .github/workflows/documentation-deploy.yml, .github/workflows/example-java-test.yml, .github/workflows/integration-test.yml
- Remove paths-ignore configuration for push event across multiple workflow files
- Simplify workflow configurations by removing redundant sections
- This change allows all CI jobs to run on all pushes, improving test coverage and ensuring comprehensive validation of changes
=> ci: remove paths-ignore for push event and simplify workflow configurations

.github/workflows/codecov.yml
- Add paths-ignore for push event
- Ignore 'document', 'documentation', 'schema', and 'wow-example' folders
- Improve workflow efficiency by excluding unnecessary files
=> ci: ignore additional folders in Codecov workflow

.idea/inspectionProfiles/Project_Default.xml, .idea/kotlinc.xml, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt
- Update Kotlin plugin version to 2.1.21
- Add new inspection tool settings
- Implement KClass support in test stages for better type safety
- Add expectEventType and expectErrorType functions using KClass
- Update nextEvent and nextCommand functions to use KClass
- Improve code readability and reduce boilerplate with reified type parameters
=> refactor(test): enhance type safety and usability with Kotlin reflections

wow-elasticsearch/src/main/kotlin/me/ahoo/wow/elasticsearch/query/AbstractElasticsearchQueryService.kt
- Update AbstractElasticsearchQueryService to use next() instead of single()
- This change improves the handling of single element queries in Elasticsearch
=> refactor(wow-elasticsearch): replace single() with next() for dynamicSingle

example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrchestrationTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrderSagaTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrderTest.kt
- Remove unnecessary expectEventCount() calls
- Use expectEventType() instead of expectEventType() for consistency
- Add missing expectCommandType() assertion in CartSagaTest
- Simplify object initialization in OrderSagaTest
- Standardize error type assertions across multiple test files
=> test: simplify and standardize test assertions

example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/AccountKTest.kt
- Replace `when` with `whenCommand` for better clarity
- Use `expectEventType` instead of `expectEvent` for consistency
- Remove unnecessary backticks around method names
=> test(example-transfer): improve test readability with extension functions

wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt
- Enable Option.EXTRA_OPEN_API_FORMAT_VALUES in OpenAPISchemaBuilder
=> feat(schema): add extra OpenAPI format values support

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/CountSnapshotRouteSpec.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/TypeFieldPaths.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/WowModule.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedCondition.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedConditionDefinitionProvider.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/AggregatedFieldPathsTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedCondition.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedFields.json
- Introduce AggregatedCondition interface for query conditions in aggregated contexts
- Implement AggregatedConditionDefinitionProvider to generate JSON schema for aggregated conditions
- Update AggregatedFieldsDefinitionProvider to use new commandAggregatedFieldPaths method
- Modify OpenAPI component to use new aggregatedCountQueryRequestBody method
- Rename AggregatedFieldPaths to TypeFieldPaths and add new methods for state and command aggregated field paths
=> feat(schema): add support for aggregated query conditions

wow-schema/src/main/kotlin/me/ahoo/wow/schema/TypeFieldPaths.kt, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedCondition.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedFields.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedListQuery.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedPagedQuery.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedSingleQuery.json
- Add aggregateId, tenantId, ownerId, version, deleted, and state fields to the enum lists in OrderAggregatedCondition, OrderAggregatedFields, and related query schemas
- Update TypeFieldPaths to include new fields in the ALL_FIELD_PATHS list for OrderAggregated
=> feat(schema): add common fields to OrderAggregated query schemas

wow-schema/src/main/kotlin/me/ahoo/wow/schema/TypeFieldPaths.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/AggregatedFieldPathsTest.kt
- Add support for Jackson's @JsonIgnore annotation in TypeFieldPaths
- Filter out properties annotated with @JsonIgnore when building field paths
- Improve compatibility with Jackson-based serialization/deserialization
=> feat(schema): support Jackson @JsonIgnore annotation

wow-schema/build.gradle.kts, wow-schema/src/main/kotlin/me/ahoo/wow/schema/TypeFieldPaths.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/AggregatedFieldPathsTest.kt
- Add support for polymorphic types using JsonSubTypes annotation
- Implement allFieldPathsForPolymorphic test case
- Modify allFieldPaths to use a set instead of a list to avoid duplicates
- Filter out static properties from field paths
- Update dependencies to include wow-models
=> feat(schema): add polymorphic type support and improve field path handling

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/RouterSpecsTest.kt, wow-spring-boot-starter/build.gradle.kts, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/openapi/OpenAPIAutoConfiguration.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/openapi/WowOpenApiCustomizer.kt
- Add springdoc-openapi-starter-common dependency
- Refactor OpenAPIAutoConfiguration to use WowOpenApiCustomizer
- Update RouterSpecs to support merging OpenAPI
- Create WowOpenApiCustomizer to customize OpenAPI using RouterSpecs
=> build(wow-spring-boot-starter): integrate springdoc-openapi for OpenAPI customization

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/WowSchemaConverter.kt
- Remove `current.finish()` call which is not required when using `schema()` method
=> fix(wow-openapi): remove unnecessary schema finish call

wow-core/src/main/kotlin/me/ahoo/wow/naming/CurrentContextCapable.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/context/CurrentOpenAPIComponentContext.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverter.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/WowAutoConfiguration.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/openapi/OpenAPIAutoConfigurationTest.kt
- Extract CurrentContextCapable interface for managing current context
- Refactor CurrentBoundedContext and CurrentOpenAPIComponentContext to implement CurrentContextCapable
- Update BoundedContextSchemaNameConverter to use new current property
- Modify WowAutoConfiguration to set current context using CurrentBoundedContext
=> refactor(naming): introduce CurrentContextCapable interface for context management

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/WowAutoConfiguration.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/WowAutoConfigurationTest.kt
- Add ErrorConverterRegistrar bean creation in WowAutoConfiguration
- Implement and test ErrorConverterFactory with Throwable support
- Update WowAutoConfigurationTest to include new ErrorConverterRegistrar bean
=> feat(exception): support auto register ErrorConverterFactory to ErrorConverterRegistrar

wow-api/src/main/kotlin/me/ahoo/wow/api/query/MaterializedSnapshot.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/query/SmallMaterializedSnapshot.kt
- Add IMaterializedSnapshot interface to define materialized snapshot behavior
- Implement IMaterializedSnapshot in MaterializedSnapshot and SmallMaterializedSnapshot
- Remove direct implementation of StateCapable and Materialized from snapshots
- This change improves code organization and enables more flexible snapshot handling
=> feat(api): introduce IMaterializedSnapshot interface and simplify snapshots

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/converter/BoundedContextSchemaNameConverter.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/JsonSchemaGeneratorTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Update BoundedContextSchemaNameConverter to handle non-array types
- Add test case for array type in JsonSchemaGenerator
- Improve SchemaReference merge function to support array references
- Add test case for array type in OpenAPISchemaBuilder
=> fix(schema): support array type in JSON Schema generation

wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/SchemaMerger.kt
- Introduce SchemaMerger object to handle schema merging
- Refactor OpenAPISchemaBuilder to use the new SchemaMerger
- Improve code readability and maintainability by separating concerns
=> refactor(wow-schema): optimize OpenAPI schema merging logic

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt, wow-core/build.gradle.kts, wow-core/src/main/kotlin/me/ahoo/wow/ioc/ServiceProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/FunctionAccessorMetadata.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/function/MessageFunctionAccessor.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/handler/MessageExchange.kt, wow-core/src/test/kotlin/me/ahoo/wow/ioc/SimpleServiceProviderTest.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/SpringServiceProvider.kt
- Remove InjectParameter.javaType and replace with InjectParameter.type (KType)
- Update MessageExchange.extractObject to use KType instead of Class<T>
- Modify MessageFunctionAccessor to use InjectParameter.type instead of javaType
- This change allows for more flexible type handling and avoids unnecessary Java interop
=> refactor(messaging): replace javaType with KType in MessageExchange and FunctionAccessor

test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt, wow-core/src/main/kotlin/me/ahoo/wow/infra/accessor/constructor/ObjectFactory.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/ServiceProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt, wow-spring/build.gradle.kts, wow-spring/src/main/kotlin/me/ahoo/wow/spring/SpringServiceProvider.kt, wow-spring/src/test/kotlin/me/ahoo/wow/spring/SpringServiceProviderTest.kt
- Add support for reified types in ServiceProvider
- Implement new getRequiredService methods with better error messages
- Update ObjectFactory to use new reified type methods
- Refactor SimpleServiceProvider to use KType instead of Class
=> refactor(ioc): improve ServiceProvider with reified type support

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/ServiceProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt, wow-core/src/test/kotlin/me/ahoo/wow/ioc/SimpleServiceProviderTest.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/SpringServiceProvider.kt, wow-spring/src/test/kotlin/me/ahoo/wow/spring/SpringServiceProviderTest.kt
- Simplified ServiceProvider interface with a single register method
- Updated register method signature to be more intuitive
- Modified implementations in SimpleServiceProvider and SpringServiceProvider
- Adjusted usage in DefaultAggregateVerifier and DefaultStatelessSagaVerifier
=> refactor(ioc): simplify ServiceProvider interface and update related classes

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/DefaultAggregateVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/Stages.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt
- Replace complex inject method with a simpler extension function
- Update DefaultAggregateVerifier and DefaultStatelessSagaVerifier to use new inject method
- Modify Stages.kt files to include new inject extension function
- Remove unused KType import
=> refactor(test): simplify service injection in test verifiers

compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedTest.kt
- Inject IRetrySpec and NextRetryAtCalculator using wow.ioc.register
- Remove direct instantiation of DefaultNextRetryAtCalculator
- Update test to use new dependency injection approach
=> test(compensation): update ExecutionFailedTest to use IRetrySpec and NextRetryAtCalculator

documentation/docs/guide/getting-started.md
- Update the project template version from v5.13.5 to v5.18.6 in the getting started guide
- Ensure users download the correct template version for their IDE
=> docs(guide): update project template version in getting started guide

wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/Responses.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/ResponsesKtTest.kt
- Remove unused import of toFlux() extension function
- Replace toFlux() with map() in serverSentEventStream creation
=> refactor(webflux): optimize route response handling 

wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/EventStore.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/BatchComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/CommonComponent.kt
- Replace Int.MAX_VALUE with EventStore.DEFAULT_TAIL_VERSION in OpenAPI parameters
- Add DEFAULT_TAIL_VERSION constant in EventStore companion object
- Update related components to use the new default tail version constant
=> refactor(openapi): update default tail version example in API documentation

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/ApiResponseBuilder.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/QueryComponent.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/ListQuerySnapshotRouteSpec.kt, wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/aggregate/snapshot/ListQuerySnapshotStateRouteSpec.kt
- Update ApiResponseBuilder to use ArraySchema for list content
- Modify ListQuerySnapshotRouteSpec and ListQuerySnapshotStateRouteSpec to use new schema method
- Adjust QueryComponent to use schema method for event stream response
=> fix(openapi): correct schema for list content in API responses

compensation/wow-compensation-server/src/main/kotlin/me/ahoo/wow/compensation/server/configuration/SwaggerConfiguration.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/Wow.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/WowInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/aggregate/AggregateInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/eventprocessor/EventProcessorInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/eventsourcing/EventStoreInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/CommandProducerInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/EventProducerInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/messaging/StateEventProducerInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/projection/ProjectionInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/saga/StatelessSagaInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/snapshot/SnapshotInstrumenter.kt, wow-opentelemetry/src/main/kotlin/me/ahoo/wow/opentelemetry/snapshot/SnapshotRepositoryInstrumenter.kt
- Remove INSTRUMENTATION_VERSION from WowInstrumenter
- Use Wow.VERSION in all instrumenters instead of WowInstrumenter.INSTRUMENTATION_VERSION
- Update ApplyRetrySpecComponent to use non-nullable formBuilder
- Add SwaggerConfiguration for Wow Compensation Service
- Update Wow object to use javaClass.`package`.implementationVersion for VERSION
=> refactor(instrumentation): update instrumentation version to Wow.VERSION

wow-api/src/main/kotlin/me/ahoo/wow/api/Wow.kt
- Change VERSION property to use orEmpty() instead of providing a best practices
=> refactor(api): update version retrieval and default value

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/RouterSpecs.kt, wow-openapi/src/test/kotlin/me/ahoo/wow/openapi/RouterSpecsTest.kt
- Add null check for OpenAPI.info and initialize if null
- Update RouterSpecsTest with new test cases for mergeOpenAPI scenarios
- Ensure existing info, paths, and components are preserved when merging
=> refactor(wow-openapi): improve RouterSpecs.mergeOpenAPI() null handling

wow-openapi/src/main/kotlin/me/ahoo/wow/openapi/context/OpenAPIComponentContext.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/SchemaGeneratorBuilder.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilder.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/SchemaGeneratorBuilderTest.kt, wow-schema/src/test/kotlin/me/ahoo/wow/schema/openapi/OpenAPISchemaBuilderTest.kt
- Lazy initialize TypeContext in SchemaGeneratorBuilder
- Update OpenAPISchemaBuilder to use SchemaGeneratorBuilder
- Adjust tests to new SchemaGeneratorBuilder implementation
=> refactor(schema): rebuild SchemaGeneratorBuilder with lazy initialization

wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/AbstractMongoConditionConverter.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/event/EventStreamConditionConverter.kt, wow-mongo/src/main/kotlin/me/ahoo/wow/mongo/query/snapshot/SnapshotConditionConverter.kt, wow-mongo/src/test/kotlin/me/ahoo/wow/mongo/query/SnapshotConditionConverterTest.kt, wow-mongo/src/test/kotlin/me/ahoo/wow/mongo/query/event/EventStreamConditionConverterTest.kt
- Introduce FieldConverter interface and implementations for event stream and snapshot
- Add convertCondition method to AbstractMongoConditionConverter
- Update EventStreamConditionConverter and SnapshotConditionConverter to use field converters
- Add test cases for ID field conversion in EventStreamConditionConverter
- Update existing tests to cover new field conversion functionality
=> feat(query): add field conversion for MongoDB conditions

compensation/wow-compensation-dashboard/src/app/api/EventStreamQuery.ts, compensation/wow-compensation-dashboard/src/app/api/ListQuery.ts, compensation/wow-compensation-dashboard/src/app/api/PagedQuery.ts, compensation/wow-compensation-dashboard/src/app/failed-list/failed-list.component.ts
- Remove `_id` from EventStreamQuery projection
- Replace `initialPagedQuery` with `initialSnapshotPagedQuery` in failed-list component
- Remove unused `initialListQuery` from ListQuery.ts
- Update `initialSnapshotPagedQuery` in PagedQuery.ts
=> refactor(api): adjust queries and remove unused initial queries

.editorconfig
- Replace JUnit and Hamcrest imports with AssertJ for cleaner and more fluent assertions
- This change improves code readability and simplifies imports
=> build: update import on demand settings for Kotlin

.github/workflows/package-deploy.yml, build.gradle.kts
- Update nexusPublishing configuration in build.gradle.kts
- Modify GitHub Actions workflow to use new Sonatype credentials
- Rename environment variables to reflect correct credential names
=> build(ci): update Sonatype publishing configuration

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandExchange.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/handler/MessageExchange.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/command/SimpleCommandAggregate.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/SimpleClientCommandExchangeTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/SimpleServerCommandExchangeTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/event/SimpleDomainEventExchangeTest.kt
- Add AGGREGATE_VERSION_KEY constant in CommandExchange
- Implement setAggregateVersion and getAggregateVersion methods in ServerCommandExchange
- Update MessageExchange to support getting aggregate version from Version message
- Add unit tests for SimpleClientCommandExchange and SimpleDomainEventExchange
- Update SimpleCommandAggregate to set and update aggregate version
=> feat(core): add aggregate version support

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitSignal.kt
- Add aggregateVersion property to CommandResult and WaitSignal classes
- Implement NullableAggregateVersionCapable interface in WaitSignal
- Update MonoCommandWaitNotifier to handle aggregate version
- Modify WaitSignalData and its builder to include aggregate version
=> feat(core): add aggregate version to CommandResult and WaitSignal

example/example-domain/src/main/kotlin/me/ahoo/wow/example/domain/cart/Cart.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/RequestExceptionHandler.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/Responses.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandFacadeHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandlerFunction.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandResponses.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/DefaultExceptionHandlerTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandResponsesTest.kt
- Extract command response handling logic to new CommandResponses.kt file
- Add unit tests for command response handling in CommandResponsesTest.kt
- Update DefaultRequestExceptionHandler to handle CommandResultException
- Remove redundant code from Responses.kt
=> refactor(webflux): move command response handling to new file

wow-api/src/main/kotlin/me/ahoo/wow/api/exception/ErrorInfoCapable.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandExceptions.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/exception/ErrorConverter.kt, wow-core/src/main/kotlin/me/ahoo/wow/exception/ErrorConverterRegistrar.kt, wow-core/src/test/kotlin/me/ahoo/wow/exception/ErrorConverterRegistrarTest.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/RequestExceptionHandler.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/DefaultExceptionHandlerTest.kt
- Add ErrorInfoCapable interface to standardize error information retrieval
- Implement ErrorInfoCapable in CommandResultException
- Update ErrorConverter to handle ErrorInfoCapable objects
- Remove redundant error handling logic in RequestExceptionHandler
- Add unit tests for new error handling approach
=> feat(exception): introduce ErrorInfoCapable interface for unified error handling

wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/GlobalExceptionHandler.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/exception/HttpHeadersGuard.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/GlobalExceptionHandlerTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/exception/HttpHeadersGuardTest.kt
- Introduce trySetHeader extension function for ServerHttpResponse
- Update GlobalExceptionHandler to use trySetHeader
- Add unit tests for trySetHeader behavior
- Refactor HttpHeadersGuard to use trySet instead of set
=> refactor(exception): optimize error handling and response header setting

wow-api/src/main/kotlin/me/ahoo/wow/api/exception/ErrorInfo.kt
- Add @JsonInclude annotation to ErrorInfo class
- Apply @get:JsonInclude(JsonInclude.Include.NON_EMPTY) to bindingErrors property
- This change improves JSON serialization by including non-empty lists only
=> refactor(wow-api): add JsonInclude annotation for ErrorInfo

wow-api/src/main/kotlin/me/ahoo/wow/api/query/Condition.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/query/ListQuery.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/query/PagedQuery.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/query/SingleQuery.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/query/SortCapable.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/AggregatedFields.kt, wow-schema/src/main/kotlin/me/ahoo/wow/schema/typed/query/AggregatedCondition.kt, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedCondition.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedListQuery.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedPagedQuery.json, wow-schema/src/test/resources/META-INF/wow-schema/OrderAggregatedSingleQuery.json
- Add JsonInclude annotation to Condition class properties
- Remove explicit JsonInclude annotations from ListQuery, PagedQuery, and SingleQuery
- Add JsonInclude annotation to sort property in SortCapable interface
=> refactor(query): apply JsonInclude annotation for non-empty fields

wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/AggregateRootResolver.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/aggregate/metadata/AggregatesMetadataProcessor.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/aggregate/metadata/AggregatesMetadataResolver.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/aggregate/metadata/AggregatesMetadataSymbolProcessorProvider.kt, wow-compiler/src/main/kotlin/me/ahoo/wow/compiler/query/StateAggregateRootResolver.kt, wow-compiler/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider, wow-compiler/src/test/kotlin/me/ahoo/wow/compiler/Compiles.kt, wow-compiler/src/test/kotlin/me/ahoo/wow/compiler/aggregate/metadata/AggregatesMetadataSymbolProcessorTest.kt
- Add AggregatesMetadataProcessor to handle aggregate metadata generation
- Implement AggregatesMetadataResolver for resolving aggregate metadata
- Create AggregatesMetadataSymbolProcessorProvider for KSP integration
- Add unit tests for aggregate metadata generation
- Update QuerySymbolProcessor to remove dependency file tracking
=> feat(aggregate): add metadata generation for aggregates

wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForTest.kt
- Implement a new test case for waiting for a projected function
- Verify that the wait strategy correctly handles projected signals
- Ensure that the last projection is properly identified and returned
=> test(wow-core): add unit test for waiting for projected function

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/webflux/WebFluxAutoConfiguration.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandHandler.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/CommandMessageParser.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/extractor/CommandBuilderExtractor.kt, wow-webflux/src/main/kotlin/me/ahoo/wow/webflux/route/command/extractor/DefaultCommandBuilderExtractor.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/handler/CommandHandlerTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandFacadeHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/DefaultCommandMessageParserTest.kt
- Add CommandBuilderExtractor interface and DefaultCommandBuilderExtractor implementation
- Update CommandMessageParser to use CommandBuilderExtractor
- Modify related tests to incorporate new command builder extraction logic
- Add commandBuilderExtractor bean in WebFluxAutoConfiguration
=> refactor(webflux): introduce CommandBuilderExtractor for command parsing

wow-cosec/src/main/kotlin/me/ahoo/wow/cosec/extractor/CoSecCommandBuilderExtractor.kt, wow-cosec/src/test/kotlin/me/ahoo/wow/cosec/extractor/CoSecCommandBuilderExtractorTest.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/cosec/CoSecAutoConfiguration.kt
- Implement CoSecCommandBuilderExtractor to extract request ID from headers
- Add request ID to command builder if present
- Update CoSecAutoConfiguration to include new extractor
- Add unit tests for CoSecCommandBuilderExtractor
=> feat(cosec): add request ID extraction for CoSec

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfiguration.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareKeyAutoRegistrar.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfigurationTest.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/prepare/PrepareKeyFactoryBean.kt
- Add PrepareKeyAutoRegistrar to scan for PrepareKey interfaces
- Implement PrepareKeyFactoryBean to create PrepareKey instances
- Update PrepareAutoConfiguration to import PrepareKeyAutoRegistrar
- Add tests for PrepareAutoConfiguration with new auto-registration functionality
=> feat(prepare): auto discover and register PrepareKey

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareKeyAutoRegistrar.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareProperties.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfigurationTest.kt
- Add `basePackages` property to `PrepareProperties` class
- Implement logic to read base packages from properties in `PrepareKeyAutoRegistrar`
- Update test cases to cover new functionality
=> feat(prepare): support customize base packages for prepare key scan

.idea/modules/compensation/wow-compensation-server/Wow.wow-compensation-server.main.iml, .idea/modules/test/wow-test/Wow.wow-test.main.iml, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrchestrationTest.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt
- Add Copyable<SimpleServiceProvider> implementation to SimpleServiceProvider class
- Override copy() function to create a deep copy of the service provider
- Update VerifiedStage interface to extend GivenStage
- Modify then() function signatures to return VerifiedStage instead of GivenStage
- Update handle function parameters to use VerifiedStage instead of GivenStage
=> feat(core): implement Copyable interface for SimpleServiceProvider

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/ServiceProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/ioc/SimpleServiceProvider.kt, wow-spring/src/main/kotlin/me/ahoo/wow/spring/SpringServiceProvider.kt, wow-spring/src/test/kotlin/me/ahoo/wow/spring/SpringServiceProviderTest.kt
- Add Copyable<ServiceProvider> interface to ServiceProvider
- Remove Copyable implementation from SimpleServiceProvider
- Implement copy() method in SpringServiceProvider
- Update test cases to cover new copy functionality
- Simplify serviceProvider copying in VerifiedStage
=> refactor(ioc): implement Copyable interface for ServiceProvider

compensation/wow-compensation-domain/src/test/kotlin/me/ahoo/wow/compensation/domain/ExecutionFailedTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrchestrationTest.kt, example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/order/OrderTest.kt, example/transfer/example-transfer-domain/src/test/java/me/ahoo/wow/example/transfer/domain/AccountTest.java, example/transfer/example-transfer-domain/src/test/java/me/ahoo/wow/example/transfer/domain/TransferSagaTest.java, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/AccountKTest.kt, example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/TransferSagaKTest.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/ExpectStage.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt, wow-core/src/test/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunctionTest.kt, wow-models/src/test/kotlin/me/ahoo/wow/models/tree/test/CategoryTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/AggregateTracingHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadAggregateHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/state/LoadTimeBasedAggregateHandlerFunctionTest.kt
- Replace Consumer functional interface with Kotlin lambda in expect methods
- Update test files to use new lambda-based expect methods
- Remove unnecessary 'it' references in lambda expressions
=> refactor(test): replace Consumer with lambda in expect methods

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/ExpectStage.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt
- Add `verify(immediately: Boolean)` method to control immediate error throwing
- Implement lazy initialization for `cachedVerifiedStage`
- Enhance error handling by collecting and exposing expectation errors
- Update `VerifiedStage` to include `expectErrors` property
=> refactor(wow-test): improve error handling and verification process

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt
- Remove unused import of toJsonString
- Enhance event logging to use joinToString for better readability
=> test: improve event logging in DefaultAggregateDsl

example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSagaSpec.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/SagaSpec.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/dsl/NameSpecCapable.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/Dsl.kt
- Add NameSpecCapable interface to WhenDsl
- Implement name property and name function in DefaultWhenDsl
- Update SagaSpec and CartSagaSpec to use new naming feature
- Add test case for non-cart origin in CartSagaSpec
=> test(wow-test): enhance stateless saga dsl with naming capability

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/Dsl.kt
- Implement NameSpecCapable interface for GivenDsl and WhenDsl
- Add name property and name function to AbstractGivenStageDsl and DefaultWhenDsl
- Update dynamic test and container names to include specified names
- Improve test readability by displaying custom names in test structure
=> feat(test): add name specification capability to Aggregate DSL stages

test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt
- Add private setter to the name property in DefaultStatelessSagaDsl
- This change ensures that the name property can only be modified through the name() function, improving encapsulation and data integrity
=> refactor(wow-test): make DefaultStatelessSagaDsl name property read-only

test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/Stages.kt
- Deleted an extra blank line before the verify() function in the ExpectStage interface
=> refactor(test): remove unnecessary blank line in ExpectStage interface

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/ExpectStage.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/DefaultStatelessSagaVerifier.kt
- Rename `expectErrors` to `assertionErrors` for better clarity
- Refactor error handling logic to improve code structure and readability
- Remove unnecessary `assertionErrors` property from `VerifiedStage` interface
- Consolidate error checking and throwing logic
=> refactor(test): optimize error handling and naming conventions in stateless saga verifier and aggregate testing

test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt
- Implement dynamic test creation for expect stage verifications
- Add methods for expecting command stream, iterator, and other command-related assertions
- Implement error expectation methods
- Refactor DefaultExpectDsl to support new dynamic test features
=> test(wow-test): enhance stateless saga DSL for JUnit 5

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/VerifiedStage.kt
- Implement expect function in VerifiedStage interface
- Allow chaining expect calls for fluent testing
- Improve testability by providing a dedicated method for expectations
=> feat(test): add expect function to VerifiedStage

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt
- Replace single expect method with multiple overloaded expect methods for different scenarios
- Add new expect methods for state, event stream, event iterator, and error handling
- Update internal implementation to use DynamicTest for each expect case
- Improve code structure and readability by separating concerns
=> refactor(test): refactor expect method in DefaultAggregateDsl

test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt
- Replace class name with simple name for better readability
- Enhance test names with more specific information (e.g., command count, error type)
- Refactor expect functions to use a more concise and consistent naming convention
- Remove redundant code and simplify test creation
=> test(wow-test): improve test name generation and refactor expect functions

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/Dsl.kt
- Add parameters to on() method: aggregateId, tenantId, stateAggregateFactory, eventStore, serviceProvider
- Update DefaultAggregateDsl to use new parameters in aggregateVerifier
- Modify Dsl to include new parameters in AggregateDsl interface
=> refactor(test): enhance AggregateDsl with additional parameters

example/example-domain/src/test/kotlin/me/ahoo/wow/example/domain/cart/CartSpec.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/Dsl.kt
- Add optional name parameter to fork function in Dsl.kt
- Update DefaultAggregateDsl.kt to use custom fork name in test display
- Modify CartSpec.kt to use named fork for better test readability
=> test(aggregate): enhance fork test with custom name

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/saga/stateless/dsl/DefaultStatelessSagaDsl.kt
- Simplify service registration by using copyTo function in DefaultAggregateDsl and DefaultStatelessSagaDsl
- Remove redundant forEach loop that registered each service individually
- Improve code readability and reduce boilerplate
=> refactor(test): replace service registration loop with copyTo function

example/transfer/example-transfer-domain/src/test/kotlin/me/ahoo/wow/example/transfer/domain/TransferSagaSpec.kt
- Replace TransferSagaKTest with TransferSagaSpec using SagaSpec
- Update test cases for Prepared, AmountEntered, and EntryFailed events
- Improve test assertions for command type and body
=> test(transfer): migrate TransferSaga tests to SagaSpec

documentation/docs/reference/example/transfer.md
- Replace traditional unit tests with SagaSpec for TransferSaga
- Simplify test structure and improve readability
- Maintain test coverage for Prepared, AmountEntered, and EntryFailed events
=> refactor(TransferSaga): update unit tests to use SagaSpec

test/wow-test/src/main/kotlin/me/ahoo/wow/test/aggregate/dsl/DefaultAggregateDsl.kt, test/wow-test/src/main/kotlin/me/ahoo/wow/test/dsl/NameSpecCapable.kt
- Move appendName logic to NameSpecCapable.Companion for reuse
- Replace repeated code in DefaultAggregateDsl with appendName calls
- Improve code readability and maintainability
=> refactor(test): extract appendName function to NameSpecCapable companion object

wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/reactor/Monos.kt
- Simplify check function using thenRunnable
- Refactor send function to use thenDefer and thenRunnable
- Introduce new reactive extensions in Monos.kt for better code organization
=> refactor(wow-core): optimize command gateway and introduce reactive extensions

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandStage.kt
- Replace inheritance with composition to simplify the class hierarchy
- Introduce 'previous' property to represent prerequisite stages
- Update logic for shouldNotify and isAfter methods to use the new chain structure
- Remove redundant code and improve readability
=> refactor(wow-core): refactor CommandStage with chain structure

wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingFor.kt
- Move wait strategy injection from DefaultCommandGateway to WaitingFor class
- Add inject method to WaitStrategy interface
- Implement inject method in WaitingFor class
- Update command processing logic in DefaultCommandGateway
=> refactor(wow-core): improve wait strategy injection in command gateway

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandStage.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingFor.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/DefaultCommandGatewayTest.kt
- Remove requirement for waitStrategy to be WaitingFor
- Remove special handling for void commands
- Delete related test case for void command validation
=> refactor(command): remove void command checks in DefaultCommandGateway

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- Rename AbstractWaitStrategy class to WaitingFor
- Update related imports and references
- Adjust logger initialization to companion object
=> refactor(wow-core): rename AbstractWaitStrategy to WaitingFor

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagator.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifierTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagatorTest.kt
- Move COMMAND_WAIT constants to WaitingForStage companion object
- Extract injectWaitStrategy logic into WaitingForStage
- Update related tests and classes to use new WaitingForStage.inject method
- Remove redundant injectWaitStrategy function from Header
=> refactor(wow-core): move wait strategy constants and logic to WaitingForStage

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForStageTest.kt
- Rename WaitingForTest.kt to WaitingForStageTest.kt
- Add new test cases for WaitingForStage:
- processedInject
- extractWaitingForStageIfNotExistEndpoint
- extractWaitingForStageIfNotExistStage
- Update existing test cases to use new extractWaitingForStage function
=> test(wow-core): rename test file and add new test cases for WaitingForStage

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForAfterProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForProjected.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForSnapshot.kt
- Rename isWaitingForSignal to shouldNotify for better clarity
- Implement WaitSignalShouldNotifyPredicate in WaitingForAfterProcessed
- Update related classes to use the new method name
- Improve code readability and maintainability
=> refactor(wow-core): rename and implement WaitSignalShouldNotifyPredicate

wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt
- Update commandGateway call in StatelessSagaFunction to use send() instead of sendAndWaitForSent()
- This change improves the performance and responsiveness of the stateless saga function
=> refactor(wow-core): replace sendAndWaitForSent with send in StatelessSagaFunction

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForAfterProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForSnapshot.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- Add tryEmit function to handle emit operations with termination checks
- Implement fail-fast logic in WaitingForStage for unsuccessful signals
- Remove redundant success check in WaitingForAfterProcessed
- Update error and completion handling in WaitingFor class
=> refactor(wow-core): improve error handling and signaling in WaitingFor classes

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFor.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- Introduce `isPreviousSignal` abstract method in WaitingFor interface
- Implement `isPreviousSignal` in WaitingForStage class
- Update `nextSignal` method to use `isPreviousSignal` for failure detection
=> refactor(wow-core): abstract previous signal logic in WaitingFor

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt
- Add notifyAndForget extension function to CommandWaitNotifier
- Update MonoCommandWaitNotifier to use the new extension function
- Simplify notification logic by moving shouldNotify check into the new function
=> refactor(wow-core): optimize wait strategy notification logic

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandFactory.kt, wow-core/src/main/kotlin/me/ahoo/wow/event/DomainEventStreamFactory.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/CommandOperatorMessagePropagator.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/CommandRequestHeaderPropagator.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/MessagePropagator.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/MessagePropagatorProvider.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/TraceMessagePropagator.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagator.kt, wow-core/src/main/kotlin/me/ahoo/wow/saga/stateless/StatelessSagaFunction.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/CommandOperatorMessagePropagatorTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/CommandRequestHeaderPropagatorTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/MessagePropagatorProviderTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/TraceMessagePropagatorTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagatorTest.kt, wow-cosec/src/main/kotlin/me/ahoo/wow/cosec/propagation/CoSecMessagePropagator.kt, wow-cosec/src/test/kotlin/me/ahoo/wow/cosec/propagation/CoSecMessagePropagatorTest.kt
- Rename inject() method to propagate() in MessagePropagator interface
- Update related classes and tests to use new propagate() method
- Improve method naming consistency across the codebase
=> refactor(messaging): rename inject to propagate in MessagePropagator

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt, wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagator.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifierTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForStageTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagatorTest.kt
- remove the SimpleCommandWaitEndpoint class
- add a EndpointWaitWaitStrategy class to encapsulate the waiting policy and endpoint information
- modify the extractWaitStrategy method in Header to return a new EndpointWaitWaitStrategy object
- update the logic in CommandWaitNotifier and DefaultCommandGateway, use the new waiting policy object
- refactor the WaitingForStage class, use the Materialized class to encapsulate serialized information
- update the WaitStrategyMessagePropagator to support the new waiting policy propagation mechanism
=> refactor(command): Refactor the command waiting policy propagation mechanism

wow-core/src/main/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagator.kt, wow-core/src/test/kotlin/me/ahoo/wow/messaging/propagation/WaitStrategyMessagePropagatorTest.kt
- Early exit for non-CommandMessages when WaitingForStage is not used
- This change improves performance by reducing unnecessary processing
=> perf(messaging): optimize WaitStrategyMessagePropagator for non-CommandMessages

wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/ApplicationBasePackageScanner.kt, wow-spring-boot-starter/src/main/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareKeyAutoRegistrar.kt, wow-spring-boot-starter/src/test/kotlin/me/ahoo/wow/spring/boot/starter/prepare/PrepareAutoConfigurationTest.kt
- Change bean name from prepare key metadata name to proxy interface simple name
- Update PrepareAutoConfigurationTest to use new bean name
- Modify PrepareKeyAutoRegistrar to register bean with new name
=> fix(prepare): update bean name to proxy interface simple name

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFors.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForAfterProcessed.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForProjected.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- Update CommandWaitNotifier to use new notification logic
- Refactor WaitingForAfterProcessed to use isWaitingFor method
- Modify WaitingForFunction to use isWaitingForFunction extension function
- Update WaitingForProjected to use isWaitingFor method
- Add new WaitingFors file with isWaitingForFunction extension function
- Update WaitingForStage to use new waiting logic
=> refactor(wow-core): improve wait strategy notification logic

test/wow-tck/src/main/kotlin/me/ahoo/wow/tck/command/CommandGatewaySpec.kt, wow-api/src/main/kotlin/me/ahoo/wow/api/modeling/NamedAggregate.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/NotifierFilters.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitSignal.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/DefaultAggregateId.kt, wow-core/src/main/kotlin/me/ahoo/wow/modeling/MaterializedNamedAggregate.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/CommandResultTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/LocalCommandWaitNotifierTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SimpleWaitStrategyRegistrarTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForStageTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/exception/ErrorConverterRegistrarTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/ResponsesKtTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/command/CommandResponsesTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/wait/CommandWaitHandlerFunctionTest.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/wait/WebClientCommandWaitNotifierTest.kt
- Add FunctionInfoData and AggregateId to CommandResult
- Update related tests and components to accommodate new fields
- Adjust WaitSignal to include AggregateId
- Refactor CommandGateway to use new CommandResult structure
=> refactor(command): enrich CommandResult with FunctionInfo and AggregateId

wow-core/src/main/kotlin/me/ahoo/wow/command/CommandGateway.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/CommandResult.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/DefaultCommandGateway.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/CommandResultTest.kt
- Extract COMMAND_GATEWAY_FUNCTION as a constant
- Update CommandMessage to use COMMAND_GATEWAY_FUNCTION instead of commandGatewayFunction()
- Modify CommandResult to use COMMAND_GATEWAY_FUNCTION by default
- Update tests to reflect the changes
=> refactor(command): optimize CommandGateway and CommandResult

wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/AggregateSnapshotDispatcher.kt, wow-core/src/main/kotlin/me/ahoo/wow/eventsourcing/snapshot/SnapshotDispatcher.kt, wow-webflux/src/test/kotlin/me/ahoo/wow/webflux/route/compensation/EventCompensateHandlerFunctionTest.kt
- Extract SNAPSHOT_FUNCTION as a constant
- Update contextName and processorName in AggregateSnapshotDispatcher
- Modify EventCompensateHandlerFunctionTest to use SNAPSHOT_FUNCTION constant
- Remove snapshotFunction() from NamedAggregate
=> refactor(eventsourcing): standardize snapshot function information

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/MonoCommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitSignal.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/SagaHandledNotifierFilterTest.kt
- Add getCommandSize() method to MonoCommandWaitNotifier
- Update WaitSignal interface and SimpleWaitSignal class to include commandSize
- This enhancement allows tracking the number of commands emitted by Saga
=> feat(wow-core): add command size information to WaitSignal

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitingFors.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForEventHandled.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForFunction.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForProjected.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForSagaHandled.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForStageTest.kt, wow-core/src/test/kotlin/me/ahoo/wow/command/wait/WaitingForsTest.kt
- Introduce NamedFunctionInfoData to encapsulate function information
- Update WaitingForFunction and related classes to use NamedFunctionInfoData
- Modify isWaitingForFunction to use NamedFunctionInfoData
- Adjust WaitingForStage.Materialized to handle function information
- Update related tests to accommodate the new structure
=> refactor(wow-core): replace contextName, processorName, functionName with function object

wow-api/src/main/kotlin/me/ahoo/wow/api/naming/CompletedCapable.kt
- Move CompletedCapable interface from wow-models to wow-api-naming module
- Update import in wow-models to use the new location of CompletedCapable
=> refactor(models): move CompletedCapable to api-naming module

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/WaitStrategy.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/stage/WaitingForStage.kt
- Move propagate(header: Header, upstream: Message<*, *>) method from WaitingForStage to WaitStrategy
- Remove redundant import statements in WaitingForStage.kt
=> refactor(wow-core): move message propagation logic

wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitEndpoint.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/CommandWaitNotifier.kt, wow-core/src/main/kotlin/me/ahoo/wow/command/wait/ExtractedWaitStrategy.kt
- Move CommandWaitEndpoint and related classes to new file
- Create new file for ExtractedWaitStrategy and related functions
- Simplify CommandWaitNotifier class
=> refactor(wow-core): split CommandWaitNotifier into separate files

compensation/dashboard/src/components/Failed/FailedView.tsx, compensation/dashboard/src/components/Failed/details/FetchingFailedDetails.tsx
- Add useQueryParams and useGlobalDrawer hooks to FailedView
- Implement logic to open GlobalDrawer with FetchingFailedDetails component when id query param is present
- Update FetchingFailedDetails to use Identifier type for id prop
=> feat(compensation): add execution failed details functionality

compensation/dashboard/package.json, compensation/dashboard/pnpm-lock.yaml, compensation/dashboard/src/features/Failed/Actions.tsx, compensation/dashboard/src/features/Failed/ApplyRetrySpec.tsx, compensation/dashboard/src/features/Failed/ChangeFunction.tsx, compensation/dashboard/src/features/Failed/FailedView.tsx, compensation/dashboard/src/features/Failed/MarkRecoverable.tsx, compensation/dashboard/src/services/compensationFetcher.ts, compensation/dashboard/src/services/executionFailedCommandClient.ts, compensation/dashboard/src/services/executionFailedQueryClient.ts, compensation/dashboard/src/services/executionFailedState.ts
- Renamed ExecutionFailedCommandService to ExecutionFailedCommandClient
- Updated import statements to use executionFailedCommandClient
- Changed ClientOptions to ApiMetadata in compensationFetcher.ts
- Upgraded @ahoo-wang/fetcher dependencies from 1.9.8 to 2.0.0
- Modified ExecutionFailedFields from class to enum
- Adjusted command client instantiation and method calls
- Fixed import formatting in executionFailedState.ts
- Added missing comma in FailedView.tsx condition block
=> refactor(services): rename service to client and update dependencies

example/example-api/src/main/kotlin/me/ahoo/wow/example/api/cart/MockVariableCommand.kt
- Updated command route action placeholder from {enum} to {mockEnum}
- Renamed enum parameter to mockEnum in MockVariableCommand data class
- Maintained all existing command route configurations and mappings
=> refactor(demo): rename enum path variable to mockEnum

documentation/docs/guide/getting-started.md
- Updated wow-project-template.zip download URL from v6.2.0 to v6.2.1
- Maintained all other documentation content and structure unchanged
=> docs(guide): update project template download link

compensation/dashboard/package.json, compensation/dashboard/pnpm-lock.yaml
- Updated @ahoo-wang/fetcher from2.3.5 to2.3.6
- Updated @ahoo-wang/fetcher-cosec from2.3.5 to2.3.6
- Updated @ahoo-wang/fetcher-decorator from2.3.5 to2.3.6
- Updated @ahoo-wang/fetcher-eventstream from 2.3.5 to2.3.6
- Updated @ahoo-wang/fetcher-wow from 2.3.5 to2.3.6
- Updated @ahoo-wang/fetcher-generator from 2.3.5 to2.3.6
- Updated @types/react from 19.1.14 to19.1.15
- Updated baseline-browser-mapping from 2.8.8 to2.8.9
=> chore(deps): update fetcher dependencies to v2.3.6

compensation/dashboard/package.json, compensation/dashboard/pnpm-lock.yaml
- Updated @ahoo-wang/fetcher packages from 2.5.0 to2.5.3
- Updated @ahoo-wang/fetcher-cosec from2.5.0 to2.5.3
- Updated @ahoo-wang/fetcher-decorator from2.5.0 to2.5.3- Updated @ahoo-wang/fetcher-eventstream from 2.5.0 to2.5.3- Updated @ahoo-wang/fetcher-wow from2.5.0 to2.5.3- Updated @ahoo-wang/fetcher-generator from2.5.0 to2.5.3
- Updated typescript-eslint from 8.44.1 to8.45.0
- Updated related dependency versions in pnpm-lock.yaml
=> chore(deps): update fetcher and typescript-eslint dependencies

compensation/dashboard/package.json, compensation/dashboard/pnpm-lock.yaml
- Updated @ahoo-wang/fetcher from2.5.3 to2.5.5
- Updated @ahoo-wang/fetcher-cosec from2.5.3 to2.5.5
- Updated @ahoo-wang/fetcher-decorator from2.5.3 to2.5.5
- Updated @ahoo-wang/fetcher-eventstream from2.5.3 to2.5.5
- Updated @ahoo-wang/fetcher-wow from 2.5.3 to2.5.5
- Updated @ahoo-wang/fetcher-generator from 2.5.3 to2.5.5
- Updated corresponding lock file entries for all fetcher packages
=> chore(deps): update fetcher dependencies to v2.5.5
